"""Non-authoritative AI observation and solver-control-plane namespace."""

from structural_analysis.ai.shadow_solver_controller import (
    DeterministicResidualStepPolicy,
    ShadowSolverControllerError,
    ShadowSolverControllerRun,
    ShadowStepDecision,
    ShadowStepInput,
    ShadowStepPolicy,
    build_shadow_step_solver_episode,
)
from structural_analysis.ai.fiber_frame_solver_episode_adapter import (
    FIBER_FRAME_SOLVER_EPISODE_ADAPTER_SCHEMA_VERSION,
    FIBER_FRAME_SOLVER_EPISODE_AUTHORITY_PROFILE,
    FiberFrameSolverEpisodeAdapter,
    FiberFrameSolverEpisodeAdapterError,
    FiberFrameSolverEpisodeObservationBinding,
    FiberFrameSolverEpisodeTransitionBinding,
    create_fiber_frame_solver_episode_adapter,
    validate_fiber_frame_solver_episode_adapter,
    validate_fiber_frame_solver_episode_adapter_manifest,
    validate_fiber_frame_solver_episode_adapter_shape,
)
from structural_analysis.ai.offline_counterfactual import (
    COUNTERFACTUAL_OUTCOME_SCHEMA_VERSION,
    FIBER_FRAME_COUNTERFACTUAL_EVALUATOR_PROFILE,
    OFFLINE_COUNTERFACTUAL_CLAIM_BOUNDARY,
    OFFLINE_COUNTERFACTUAL_DATASET_SCHEMA_VERSION,
    OFFLINE_COUNTERFACTUAL_PROFILE,
    SHADOW_POLICY_SCORECARD_SCHEMA_VERSION,
    CounterfactualTransitionOutcome,
    DatasetSplit,
    OfflineCounterfactualDataset,
    OfflineCounterfactualError,
    OfflineCounterfactualSource,
    OfflineSourceKind,
    ShadowPolicyScorecard,
    build_offline_counterfactual_dataset,
    build_shadow_policy_scorecard,
    replay_fiber_frame_counterfactual_transition,
    validate_offline_counterfactual_dataset,
    validate_shadow_policy_scorecard,
)

# Preserve the originally documented short names while exporting the concrete
# controller names used by the implementation module.
ShadowControllerError = ShadowSolverControllerError
build_shadow_solver_episode = build_shadow_step_solver_episode

__all__ = [
    "FIBER_FRAME_SOLVER_EPISODE_ADAPTER_SCHEMA_VERSION",
    "FIBER_FRAME_SOLVER_EPISODE_AUTHORITY_PROFILE",
    "COUNTERFACTUAL_OUTCOME_SCHEMA_VERSION",
    "FIBER_FRAME_COUNTERFACTUAL_EVALUATOR_PROFILE",
    "OFFLINE_COUNTERFACTUAL_CLAIM_BOUNDARY",
    "OFFLINE_COUNTERFACTUAL_DATASET_SCHEMA_VERSION",
    "OFFLINE_COUNTERFACTUAL_PROFILE",
    "SHADOW_POLICY_SCORECARD_SCHEMA_VERSION",
    "CounterfactualTransitionOutcome",
    "DeterministicResidualStepPolicy",
    "DatasetSplit",
    "FiberFrameSolverEpisodeAdapter",
    "FiberFrameSolverEpisodeAdapterError",
    "FiberFrameSolverEpisodeObservationBinding",
    "FiberFrameSolverEpisodeTransitionBinding",
    "OfflineCounterfactualDataset",
    "OfflineCounterfactualError",
    "OfflineCounterfactualSource",
    "OfflineSourceKind",
    "ShadowSolverControllerError",
    "ShadowSolverControllerRun",
    "ShadowControllerError",
    "ShadowStepDecision",
    "ShadowStepInput",
    "ShadowStepPolicy",
    "ShadowPolicyScorecard",
    "build_offline_counterfactual_dataset",
    "build_shadow_policy_scorecard",
    "build_shadow_step_solver_episode",
    "build_shadow_solver_episode",
    "create_fiber_frame_solver_episode_adapter",
    "replay_fiber_frame_counterfactual_transition",
    "validate_fiber_frame_solver_episode_adapter",
    "validate_fiber_frame_solver_episode_adapter_manifest",
    "validate_fiber_frame_solver_episode_adapter_shape",
    "validate_offline_counterfactual_dataset",
    "validate_shadow_policy_scorecard",
]
