[package]
name = "structural-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
native-link = ["structural-engine-sys/native-link"]

[dependencies]
structural-engine-sys = { path = "../structural-engine-sys" }
