#!/usr/bin/env python3
"""Generate calibration report for optimization objective weights."""

from __future__ import annotations

import argparse
from pathlib import Path

from design_optimization.io import load_json, write_json
from design_optimization.report_builder import build_report_payload
from design_objective_calibration import build_objective_profile_report, calibrate_objective_weights
from design_optimization_env import DesignOptimizationConfig


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--dataset-report",
        default="implementation/phase1/release/design_optimization/design_optimization_dataset_report.json",
    )
    p.add_argument(
        "--changes-summary",
        default="implementation/phase1/release/design_optimization/design_optimization_cost_reduction_changes_summary.json",
    )
    p.add_argument(
        "--solver-loop-report",
        default="implementation/phase1/release/design_optimization/design_optimization_solver_loop_long_report.json",
    )
    p.add_argument(
        "--wind-report",
        default="implementation/phase1/wind_time_history_gate_report.json",
    )
    p.add_argument(
        "--ssi-report",
        default="implementation/phase1/ssi_boundary_gate_report.json",
    )
    p.add_argument(
        "--out",
        default="implementation/phase1/release/design_optimization/design_objective_calibration_report.json",
    )
    p.add_argument("--objective-profile", default="balanced_practice")
    p.add_argument("--profile-path", default="implementation/phase1/design_objective_profiles.json")
    p.add_argument(
        "--profile-out",
        default="implementation/phase1/release/design_optimization/design_objective_profile_report.json",
    )
    args = p.parse_args()

    base_cfg = DesignOptimizationConfig()
    report = calibrate_objective_weights(
        dataset_report=load_json(Path(args.dataset_report)),
        change_summary=load_json(Path(args.changes_summary)),
        solver_loop_report=load_json(Path(args.solver_loop_report)),
        wind_report=load_json(Path(args.wind_report)),
        ssi_report=load_json(Path(args.ssi_report)),
        base_cfg=base_cfg,
    )
    payload = build_report_payload(
        run_id="phase1-design-objective-calibration",
        summary=report["signals"],
        inputs={
            "dataset_report": str(args.dataset_report),
            "changes_summary": str(args.changes_summary),
            "solver_loop_report": str(args.solver_loop_report),
            "wind_report": str(args.wind_report),
            "ssi_report": str(args.ssi_report),
        },
        artifacts={
            "report_out": str(args.out),
            "profile_out": str(args.profile_out),
        },
        contract_pass=True,
        reason_code="PASS",
        reason="design objective calibration generated",
        extra={
            "base_config": report["base_config"],
            "calibrated_config": report["calibrated_config"],
        },
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    write_json(out, payload)
    profile_report = build_objective_profile_report(
        base_cfg=base_cfg,
        calibration_report=payload,
        profile_name=str(args.objective_profile),
        profile_path=args.profile_path,
        project_type="generic",
        why_selected=f"profile overlay generated by calibration script: {args.objective_profile}",
    )
    profile_payload = build_report_payload(
        run_id="phase1-design-objective-profile",
        summary=profile_report,
        inputs={
            "objective_profile": str(args.objective_profile),
            "profile_path": str(args.profile_path),
            "calibration_report": str(args.out),
        },
        artifacts={"report_out": str(args.profile_out)},
        contract_pass=True,
        reason_code="PASS",
        reason="design objective profile generated",
        extra=dict(profile_report),
    )
    profile_out = Path(args.profile_out)
    write_json(profile_out, profile_payload)
    print(f"Wrote design objective calibration report: {out}")


if __name__ == "__main__":
    main()
