"""Versioned backend-neutral Engine v2 core contracts."""

from structural_analysis.engine_v2.contracts.equation_scaling import (
    CHARACTERISTIC_LENGTH_POLICY,
    EQUATION_SCALING_EXTENSION_KEY,
    EQUATION_SCALING_SCHEMA_VERSION,
    REFERENCE_FORCE_POLICY,
    SCALED_RESIDUAL_TRACE_SCHEMA_VERSION,
    EquationScaling,
    EquationScalingError,
    ScaledResidualTrace,
    bind_equation_scaling_to_execution_plan,
    create_equation_scaling,
    execution_plan_scaling_hash,
    trace_scaled_residual,
    validate_equation_scaling,
    validate_equation_scaling_binding,
    validate_equation_scaling_manifest,
    validate_scaled_residual_trace,
    validate_scaled_residual_trace_manifest,
)

from structural_analysis.engine_v2.contracts.execution_plan import (
    EXECUTION_PLAN_CAPABILITY_PROFILE,
    EXECUTION_PLAN_DOF_COMPONENTS,
    EXECUTION_PLAN_RESIDUAL_SIGN,
    EXECUTION_PLAN_SCHEMA_VERSION,
    ExecutionPlan,
    ExecutionPlanError,
    PlanArrayDescriptor,
    create_execution_plan,
    validate_execution_plan,
    validate_execution_plan_manifest,
)
from structural_analysis.engine_v2.contracts.state_ir import (
    STATE_IR_SCHEMA_VERSION,
    StateIR,
    StateIRError,
    commit_trial_state,
    create_initial_state,
    open_trial_state,
    rollback_trial_state,
    validate_state_ir,
    validate_state_ir_manifest,
)

__all__ = [
    "CHARACTERISTIC_LENGTH_POLICY",
    "EQUATION_SCALING_EXTENSION_KEY",
    "EQUATION_SCALING_SCHEMA_VERSION",
    "EXECUTION_PLAN_CAPABILITY_PROFILE",
    "EXECUTION_PLAN_DOF_COMPONENTS",
    "EXECUTION_PLAN_RESIDUAL_SIGN",
    "EXECUTION_PLAN_SCHEMA_VERSION",
    "REFERENCE_FORCE_POLICY",
    "SCALED_RESIDUAL_TRACE_SCHEMA_VERSION",
    "STATE_IR_SCHEMA_VERSION",
    "ExecutionPlan",
    "ExecutionPlanError",
    "EquationScaling",
    "EquationScalingError",
    "PlanArrayDescriptor",
    "ScaledResidualTrace",
    "StateIR",
    "StateIRError",
    "commit_trial_state",
    "bind_equation_scaling_to_execution_plan",
    "create_equation_scaling",
    "create_execution_plan",
    "create_initial_state",
    "execution_plan_scaling_hash",
    "open_trial_state",
    "rollback_trial_state",
    "trace_scaled_residual",
    "validate_equation_scaling",
    "validate_equation_scaling_binding",
    "validate_equation_scaling_manifest",
    "validate_execution_plan",
    "validate_execution_plan_manifest",
    "validate_scaled_residual_trace",
    "validate_scaled_residual_trace_manifest",
    "validate_state_ir",
    "validate_state_ir_manifest",
]
