"""Isolated HIPRTC backend for the Engine v2 canonical-CSR replay."""

from structural_analysis.engine_v2.rtc_backend.csr_context import (
    RTC_CSR_CAPABILITY_PROFILE,
    RTC_CSR_CONTEXT_RECEIPT_SCHEMA_VERSION,
    RTC_RESIDUAL_JVP_RECEIPT_SCHEMA_VERSION,
    HipRtcCsrContextError,
    HipRtcCsrContextOpenResult,
    HipRtcCsrContextReceipt,
    HipRtcCsrExecutionContext,
    HipRtcResidualJvpEvaluation,
    HipRtcResidualJvpReceipt,
    open_hip_rtc_csr_execution_context,
    validate_hip_rtc_csr_context_receipt,
    validate_hip_rtc_residual_jvp_evaluation,
    validate_hip_rtc_residual_jvp_receipt,
)
from structural_analysis.engine_v2.rtc_backend.rtc import (
    HIP_RTC_CSR_KERNEL_ABI_VERSION,
    HIP_RTC_CSR_KERNEL_BLOCK_SIZE,
    HIP_RTC_CSR_KERNEL_IDENTITY_SCHEMA_VERSION,
    HIP_RTC_CSR_KERNEL_NAME,
    HIP_RTC_CSR_KERNEL_SYMBOL,
    HipRtcCsrKernel,
    HipRtcCsrKernelIdentity,
    HipRtcError,
    HipRtcLibraryIdentity,
    compile_hip_rtc_csr_kernel,
)

__all__ = [
    "HIP_RTC_CSR_KERNEL_ABI_VERSION",
    "HIP_RTC_CSR_KERNEL_BLOCK_SIZE",
    "HIP_RTC_CSR_KERNEL_IDENTITY_SCHEMA_VERSION",
    "HIP_RTC_CSR_KERNEL_NAME",
    "HIP_RTC_CSR_KERNEL_SYMBOL",
    "RTC_CSR_CAPABILITY_PROFILE",
    "RTC_CSR_CONTEXT_RECEIPT_SCHEMA_VERSION",
    "RTC_RESIDUAL_JVP_RECEIPT_SCHEMA_VERSION",
    "HipRtcCsrContextError",
    "HipRtcCsrContextOpenResult",
    "HipRtcCsrContextReceipt",
    "HipRtcCsrExecutionContext",
    "HipRtcCsrKernel",
    "HipRtcCsrKernelIdentity",
    "HipRtcError",
    "HipRtcLibraryIdentity",
    "HipRtcResidualJvpEvaluation",
    "HipRtcResidualJvpReceipt",
    "compile_hip_rtc_csr_kernel",
    "open_hip_rtc_csr_execution_context",
    "validate_hip_rtc_csr_context_receipt",
    "validate_hip_rtc_residual_jvp_evaluation",
    "validate_hip_rtc_residual_jvp_receipt",
]
