include_guard(GLOBAL)

function(structural_set_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if(STRUCTURAL_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
    if(STRUCTURAL_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()

function(structural_enable_sanitizers target)
  if(NOT STRUCTURAL_ENABLE_SANITIZERS)
    return()
  endif()
  if(MSVC)
    message(FATAL_ERROR "STRUCTURAL_ENABLE_SANITIZERS requires Clang or GCC")
  endif()
  target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
  target_link_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
endfunction()
