"""Stable API entry points for local and CLI callers."""

from structural_analysis.api.core import (
    ANALYSIS_ENGINE_VERSION,
    CLAIM_BOUNDARY_VERSION,
    AnalysisConfig,
    AnalysisResult,
    ValidationReport,
    analyze,
    load_model,
)
from structural_analysis.api.nonlinear_fiber_frame import (
    PUBLIC_RC_FIBER_FRAME_CLAIM_BOUNDARY,
    PUBLIC_RC_FIBER_FRAME_COMPILER_PROFILE,
    PUBLIC_RC_FIBER_FRAME_SCHEMA_VERSION,
    PUBLIC_RC_FIBER_FRAME_SOLVER_ID,
    PublicRCFiberFrameConfig,
    PublicRCFiberFrameResult,
    PublicRCFiberFrameValidationReport,
    analyze_public_rc_fiber_frame,
    validate_public_rc_fiber_frame_result,
)
from structural_analysis.api.nonlinear_frame import (
    COROTATIONAL_GENERAL_PROFILE,
    COROTATIONAL_PORTAL_PROFILE,
    FIXED_CHORD_SERIAL_PROFILE,
    UNIFIED_NONLINEAR_FRAME_CLAIM_BOUNDARY,
    UNIFIED_NONLINEAR_FRAME_REPORT_SCHEMA_VERSION,
    UNIFIED_NONLINEAR_FRAME_SCHEMA_VERSION,
    NonlinearFrameCheckpointAdvance,
    NonlinearFrameConfig,
    NonlinearFrameControlMode,
    NonlinearFrameError,
    NonlinearFrameResult,
    NonlinearFrameValidationReport,
    advance_nonlinear_frame_checkpoint,
    analyze_nonlinear_frame,
    nonlinear_frame_resume_contract_hash,
    validate_nonlinear_frame_manifest,
    validate_nonlinear_frame_result,
)
from structural_analysis.api.nonlinear_truss import (
    PUBLIC_TWO_BAR_TRUSS_CLAIM_BOUNDARY,
    PUBLIC_TWO_BAR_TRUSS_SCHEMA_VERSION,
    PUBLIC_TWO_BAR_TRUSS_SOLVER_ID,
    PublicTwoBarTrussConfig,
    PublicTwoBarTrussResult,
    PublicTwoBarTrussValidationReport,
    analyze_public_two_bar_truss,
    validate_public_two_bar_truss_result,
)
from structural_analysis.generated_capabilities import (
    CAPABILITY_AUTHORITY_RULES,
    CAPABILITY_SCHEMA_VERSION,
    capabilities,
)
from structural_analysis.results.validation import validate

__all__ = [
    "ANALYSIS_ENGINE_VERSION",
    "CLAIM_BOUNDARY_VERSION",
    "CAPABILITY_AUTHORITY_RULES",
    "CAPABILITY_SCHEMA_VERSION",
    "PUBLIC_RC_FIBER_FRAME_CLAIM_BOUNDARY",
    "PUBLIC_RC_FIBER_FRAME_COMPILER_PROFILE",
    "PUBLIC_RC_FIBER_FRAME_SCHEMA_VERSION",
    "PUBLIC_RC_FIBER_FRAME_SOLVER_ID",
    "PUBLIC_TWO_BAR_TRUSS_CLAIM_BOUNDARY",
    "PUBLIC_TWO_BAR_TRUSS_SCHEMA_VERSION",
    "PUBLIC_TWO_BAR_TRUSS_SOLVER_ID",
    "COROTATIONAL_PORTAL_PROFILE",
    "COROTATIONAL_GENERAL_PROFILE",
    "FIXED_CHORD_SERIAL_PROFILE",
    "UNIFIED_NONLINEAR_FRAME_CLAIM_BOUNDARY",
    "UNIFIED_NONLINEAR_FRAME_REPORT_SCHEMA_VERSION",
    "UNIFIED_NONLINEAR_FRAME_SCHEMA_VERSION",
    "AnalysisConfig",
    "AnalysisResult",
    "PublicRCFiberFrameConfig",
    "PublicRCFiberFrameResult",
    "PublicRCFiberFrameValidationReport",
    "PublicTwoBarTrussConfig",
    "PublicTwoBarTrussResult",
    "PublicTwoBarTrussValidationReport",
    "NonlinearFrameConfig",
    "NonlinearFrameCheckpointAdvance",
    "NonlinearFrameControlMode",
    "NonlinearFrameError",
    "NonlinearFrameResult",
    "NonlinearFrameValidationReport",
    "ValidationReport",
    "analyze",
    "analyze_public_rc_fiber_frame",
    "analyze_public_two_bar_truss",
    "advance_nonlinear_frame_checkpoint",
    "analyze_nonlinear_frame",
    "capabilities",
    "load_model",
    "nonlinear_frame_resume_contract_hash",
    "validate",
    "validate_public_rc_fiber_frame_result",
    "validate_public_two_bar_truss_result",
    "validate_nonlinear_frame_manifest",
    "validate_nonlinear_frame_result",
]
