"""Generated capability registry. Do not edit directly."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

CAPABILITY_SCHEMA_VERSION = 'structural-analysis-capabilities.v2'
CURRENT_STATE_AUTHORITY: dict[str, Any] = {'artifact_name_pattern': 'product-state-current-{conclusion}-{source_sha}',
 'attestation_required': True,
 'manifest': 'artifacts/manifests/product_state.current.v1.json',
 'profile': 'exact-current-ci-artifact.v1',
 'source_binding': 'exact_commit_sha',
 'tracked_self_sha_authority': False,
 'tracked_snapshots': 'historical_only',
 'volatile_counts_allowed_in_registry': False,
 'workflow': '.github/workflows/product-state-current.yml'}
CAPABILITY_AUTHORITY_RULES: dict[str, Any] = {'ai_truth_owner': 'none',
 'candidate_result_authority_does_not_imply_release_eligibility': True,
 'executable_does_not_imply_numerical_promotion': True,
 'fallback_promotion_allowed': False,
 'gpu_track': 'performance_after_cpu_sparse_reference_and_external_vv',
 'implemented_does_not_imply_public': True,
 'release_requires_external_vv_level': 2,
 'release_requires_public': True,
 'solver_truth_owner': 'structural_analysis_core',
 'workbench_truth_owner': 'none'}
CAPABILITY_ROWS: tuple[dict[str, Any], ...] = ({'authority': 'validated_input_contract',
  'category': 'model_io',
  'evidence': ['tests/test_structural_analysis_core_api.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'model.neutral_canonical',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Only schema-declared entities and units are accepted.'],
  'numerical_authority': 'validated_input_contract',
  'profile': 'structural-analysis-canonical-model.v1',
  'public': True,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'supported',
  'title': 'Neutral canonical model'},
 {'authority': 'input_translation_with_provenance',
  'category': 'model_io',
  'evidence': ['src/structural_analysis/io/midas/loader.py',
               'tests/test_structural_analysis_core_api.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'io.midas_mgt',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Unsupported records remain explicit; exact native round-trip is not closed.'],
  'numerical_authority': 'input_translation_with_provenance',
  'profile': 'topology_and_supported_property_subset',
  'public': True,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'MIDAS MGT import'},
 {'authority': 'entity_scan_and_model_health_only',
  'category': 'model_io',
  'evidence': ['src/structural_analysis/io/ifc/loader.py',
               'tests/test_structural_analysis_core_api.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'io.ifc_model_health',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Not a general analysis-ready IFC structural-model compiler.'],
  'numerical_authority': 'entity_scan_and_model_health_only',
  'profile': 'ifc_step_model_health',
  'public': True,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'IFC model-health import'},
 {'authority': 'numerical_and_engineering_within_supported_elements',
  'category': 'analysis',
  'evidence': ['docs/authoritative-cpu-linear-solver.md',
               'src/structural_analysis/solvers/equation_scaling_6dof.py',
               'tests/test_structural_analysis_core_api.py',
               'tests/test_equation_scaling_6dof.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.linear_static',
  'implemented': True,
  'interfaces': ['python_api', 'cli', 'workbench'],
  'limitations': ['Dense and sparse solves use the same source-bound 6DOF force/moment row and '
                  'rotation-column scaling; scaling inputs reject coercive or value-losing '
                  'conversion to real binary64, and exact scaled condition numbers are emitted '
                  'only through 256 free equations and remain explicitly unavailable above that '
                  'bound.',
                  'No general shell, contact, staged-construction, or design-code authority.'],
  'numerical_authority': 'numerical_and_engineering_within_supported_elements',
  'profile': 'cpu_dense_or_scipy_sparse_supported_frame_truss',
  'public': True,
  'recovery_authority': 'numerical_and_engineering_within_supported_elements',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Linear static analysis'},
 {'authority': 'numerical_within_explicit_frame_truss_mass_profile',
  'category': 'analysis',
  'evidence': ['docs/phase2-whole-model-modal-analysis.md',
               'src/structural_analysis/solvers/equation_scaling_6dof.py',
               'src/structural_analysis/solvers/modal/solver.py',
               'tests/test_modal_generalized_eigen_v1.py',
               'tests/test_whole_model_modal_analysis.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.modal',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The reduced stiffness and mass matrices use source-bound 6DOF symmetric '
                  'coordinate scaling before eigen extraction; physical mode vectors are recovered '
                  'and rechecked against the original matrices.',
                  'The public default is dense and no independent Level 2 comparison is promoted.'],
  'numerical_authority': 'numerical_within_explicit_frame_truss_mass_profile',
  'profile': 'dense_symmetric_generalized_eigen_v1',
  'public': True,
  'recovery_authority': 'numerical_within_explicit_frame_truss_mass_profile',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Whole-model modal analysis'},
 {'authority': 'numerical_within_explicit_preload_profile',
  'category': 'analysis',
  'evidence': ['docs/phase2-whole-model-linear-buckling.md',
               'src/structural_analysis/solvers/equation_scaling_6dof.py',
               'src/structural_analysis/solvers/buckling/solver.py',
               'tests/test_buckling_generalized_eigen_v1.py',
               'tests/test_whole_model_buckling_analysis.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.linear_buckling',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The reduced elastic and geometric stiffness matrices use source-bound 6DOF '
                  'symmetric coordinate scaling before eigen extraction; physical buckling vectors '
                  'are recovered and rechecked against the original matrices.',
                  'The public default is dense and no independent Level 2 comparison is promoted.'],
  'numerical_authority': 'numerical_within_explicit_preload_profile',
  'profile': 'dense_symmetric_generalized_eigen_v1',
  'public': True,
  'recovery_authority': 'numerical_within_explicit_preload_profile',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Whole-model linear buckling'},
 {'authority': 'bounded_material_geometric_newton',
  'category': 'analysis',
  'evidence': ['docs/public-two-bar-nonlinear-truss.md',
               'src/structural_analysis/api/nonlinear_truss.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.nonlinear_two_bar_truss',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The profile does not generalize to arbitrary truss or frame topology.'],
  'numerical_authority': 'bounded_material_geometric_newton',
  'profile': 'symmetric_two_bar_material_geometric_v1',
  'public': True,
  'recovery_authority': 'bounded_material_geometric_newton',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Nonlinear two-bar truss'},
 {'authority': 'exact_reaction_member_section_fiber_recovery',
  'category': 'analysis',
  'evidence': ['docs/public-rc-fiber-frame.md', 'tests/test_public_rc_fiber_frame_api.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.nonlinear_rc_fiber_frame_fixed_chord',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Serial cantilever only; zero prescribed movement; dense CPU load control.'],
  'numerical_authority': 'exact_reaction_member_section_fiber_recovery',
  'profile': 'planar_serial_cantilever_explicit_rectangular_rc.v1',
  'public': True,
  'recovery_authority': 'exact_reaction_member_section_fiber_recovery',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Fixed-chord RC fiber frame'},
 {'authority': 'comparison_contract_only_no_result_promotion',
  'category': 'result_contract',
  'evidence': ['docs/engine-v2-result-quantity-contract.md',
               'src/structural_analysis/engine_v2/contracts/result_quantity.py',
               'src/structural_analysis/schemas/result_quantity_catalog_v1.schema.json',
               'tests/test_result_quantity_catalog.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'contract.result_quantity_catalog',
  'implemented': True,
  'interfaces': ['python_api', 'json_schema'],
  'limitations': ['Defines fixed SI units and comparison tolerances only; it cannot create solver '
                  'authority or make corotational output public.'],
  'numerical_authority': 'comparison_contract_only_no_result_promotion',
  'profile': 'hashed_si_quantity_catalog_and_absolute_plus_relative_linf_v1',
  'public': True,
  'recovery_authority': 'comparison_contract_only',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'ResultIR SI quantity and tolerance catalog'},
 {'authority': 'exact_bounded_candidate',
  'category': 'analysis',
  'evidence': ['docs/planar-frame-verified-alpha-v1.md',
               'src/structural_analysis/api/planar_frame.py',
               'src/structural_analysis/api/planar_frame_cli.py',
               'tests/test_planar_frame_verified_alpha_api.py',
               'tests/test_planar_frame_verified_alpha_corpus.py',
               'verification/planar_frame_verified_alpha_v1/corpus.manifest.json'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.planar_frame_verified_alpha',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['This Developer Preview row promotes only the source-bound nonlinear '
                  'load-control path; the wider linear-static, modal, and linear-buckling product '
                  'profile remains to be unified behind this API.',
                  'Direct displacement-control and arc-length remain separate experimental '
                  'profiles.',
                  'Independent external V&V, release eligibility, design-code authority, and '
                  'signed-export authority are not attached.'],
  'numerical_authority': 'exact_bounded_candidate',
  'profile': 'planar_frame_verified_alpha.v1',
  'public': True,
  'recovery_authority': 'exact_bounded_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Planar frame verified alpha'},
 {'authority': 'bounded_j1_j5_and_exact_engineering_recovery_candidate',
  'category': 'analysis',
  'evidence': ['docs/unified-nonlinear-frame-api.md',
               'docs/corotational-connected-frame2d.md',
               'docs/fiber-frame-physical-equation-scaling.md',
               'docs/corotational-fiber-frame-native-sparse.md',
               'src/structural_analysis/api/nonlinear_frame.py',
               'src/structural_analysis/adapters/bounded_planar_model_ir.py',
               'src/structural_analysis/adapters/bounded_planar_execution_plan.py',
               'src/structural_analysis/schemas/model_ir_v2.schema.json',
               'src/structural_analysis/assembly/stateful_fiber_frame2d_execution_topology.py',
               'src/structural_analysis/assembly/stateful_fiber_frame2d_physical_equation_scaling.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_general.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_sparse.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_checkpoint_chain_io.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_engineering_recovery.py',
               'src/structural_analysis/schemas/unified_nonlinear_frame_result_v1.schema.json',
               'src/structural_analysis/schemas/corotational_fiber_frame_general_j1_j5_v1.schema.json',
               '.github/workflows/engine-v2-determinism-ci.yml',
               'scripts/build_engine_v2_cross_platform_determinism_receipt.py',
               'src/structural_analysis/schemas/engine_v2_cross_platform_determinism_run_receipt_v1.schema.json',
               'src/structural_analysis/schemas/engine_v2_cross_platform_determinism_matrix_receipt_v1.schema.json',
               'src/structural_analysis/schemas/engine_v2_cross_platform_determinism_run_receipt_v2.schema.json',
               'src/structural_analysis/schemas/engine_v2_cross_platform_determinism_matrix_receipt_v2.schema.json',
               'scripts/verify_bounded_planar_wheel_smoke.py',
               '.github/workflows/opensees-calculix-current-source.yml',
               'tests/test_corotational_fiber_frame_general.py',
               'tests/test_corotational_fiber_frame_sparse.py',
               'tests/test_engine_v2_cross_platform_goldens.py',
               'tests/test_build_engine_v2_cross_platform_determinism_receipt.py',
               'tests/test_stateful_corotational_fiber_frame2d_equation_scaling.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'tests/test_bounded_planar_model_ir_adapter.py',
               'tests/test_external_code_to_code_technical_receipt.py',
               'examples/public_corotational_branching_frame.json',
               'examples/bounded_planar_frame_alpha.model-ir.v2.json',
               'examples/bounded_planar_settlement.model-ir.v2.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'docs/external-code-to-code-technical-execution.md',
               'docs/opensees-calculix-current-source-workflow.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.nonlinear_corotational_fiber_frame_2d',
  'implemented': True,
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Connected planar load-control remains experimental and non-public. '
                  'Exact-current clean-runner and cross-environment status is reported only by the '
                  'source-bound, attested Product State Current CI artifact; tracked receipts are '
                  'historical inputs and grant no current credit. Independent operator attestation '
                  'and Level 2 promotion remain absent, so external_vv_level stays 0. Direct '
                  'displacement control remains lower-level only. Prescribed-only iterative paths '
                  'with free equations and no force reference fail closed until a source-bound '
                  'kinematic reference-force scaling contract exists. No other member-feature '
                  'family, design, or release authority is created.'],
  'numerical_authority': 'bounded_j1_j5_and_exact_engineering_recovery_candidate',
  'profile': 'corotational_connected_frame2d.v1',
  'public': False,
  'recovery_authority': 'bounded_j1_j5_and_exact_engineering_recovery_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Corotational 2D fiber frame'},
 {'authority': 'bounded_native_coo_csr_and_fail_closed_exact_conditioning_candidate',
  'category': 'backend',
  'evidence': ['src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_sparse.py',
               'src/structural_analysis/solvers/nonlinear/sparse_factorization.py',
               'src/structural_analysis/solvers/nonlinear/scalable_sparse_factorization.py',
               'src/structural_analysis/schemas/sparse_factorization_diagnostic_v1.schema.json',
               'src/structural_analysis/schemas/scalable_sparse_factorization_diagnostic_v1.schema.json',
               'tests/test_corotational_fiber_frame_sparse.py',
               'tests/test_sparse_factorization_diagnostics.py',
               'tests/test_scalable_sparse_factorization.py',
               'docs/sparse-factorization-conditioning-diagnostics.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'backend.nonlinear_sparse',
  'implemented': True,
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['The public exact-conditioning path remains bounded to 256 equations. A separate '
                  'CPU-only blocked exact diagnostic is bounded to 1536 equations and is '
                  'integrated only into the bounded experimental 3D graph candidate. Exact '
                  'inverse-column conditioning has quadratic work and does not close '
                  'production-scale policy, performance or memory evidence, external V&V, or '
                  'release promotion.'],
  'numerical_authority': 'bounded_native_coo_csr_and_fail_closed_exact_conditioning_candidate',
  'profile': 'corotational_element_triplet_coalesce_sorted_csr_fp64_plus_blocked_exact_1536.v1',
  'public': False,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Native sparse nonlinear backend'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'implementation/phase1/release_evidence/productization/external_modal_buckling_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'benchmarks/clean-runners/opensees-calculix/run_clean_runner.py',
               'scripts/run_external_code_to_code_technical_receipt.py',
               'scripts/run_external_modal_buckling_technical_receipt.py',
               'scripts/run_external_vv_clean_runner.sh',
               '.github/workflows/opensees-calculix-current-source.yml',
               'scripts/validate_external_vv_operator_attestation.py',
               'scripts/promote_external_vv_level2.py',
               'scripts/build_bounded_planar_external_linear_case_package.py',
               'scripts/ingest_bounded_planar_external_linear_results.py',
               'scripts/build_bounded_planar_external_negative_case_package.py',
               'scripts/ingest_bounded_planar_external_negative_results.py',
               'scripts/build_bounded_planar_external_scaling_case_package.py',
               'scripts/ingest_bounded_planar_external_scaling_results.py',
               'scripts/build_bounded_planar_external_modal_buckling_case_package.py',
               'scripts/ingest_bounded_planar_external_modal_buckling_results.py',
               'scripts/build_bounded_planar_external_nonlinear_material_recovery_case_package.py',
               'scripts/run_bounded_planar_external_nonlinear_material_recovery_case.py',
               'scripts/ingest_bounded_planar_external_nonlinear_material_recovery_results.py',
               'scripts/build_bounded_planar_same_operator_supplemental_execution.py',
               'scripts/build_bounded_planar_external_vv_matrix.py',
               'scripts/build_bounded_planar_external_vv_matrix_from_operator_bundle.py',
               'src/structural_analysis/schemas/external_vv_operator_attestation_v1.schema.json',
               'src/structural_analysis/schemas/external_vv_level2_promotion_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_external_linear_case_package_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_opensees_linear_result_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_external_linear_execution_receipt_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_external_nonlinear_material_recovery_case_package_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_opensees_nonlinear_material_recovery_result_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_external_nonlinear_material_recovery_execution_receipt_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_same_operator_supplemental_execution_v1.schema.json',
               'src/structural_analysis/schemas/bounded_planar_external_vv_matrix_status_v1.schema.json',
               'docs/templates/external_vv_operator_attestation.template.json',
               'docs/templates/external_vv_level2_promotion.template.json',
               'tests/test_external_code_to_code_technical_receipt.py',
               'tests/test_external_modal_buckling_technical_receipt.py',
               'tests/test_external_vv_clean_runner_contract.py',
               'tests/test_validate_external_vv_operator_attestation.py',
               'tests/test_promote_external_vv_level2.py',
               'tests/test_build_bounded_planar_external_linear_case_package.py',
               'tests/test_ingest_bounded_planar_external_linear_results.py',
               'tests/test_build_bounded_planar_external_nonlinear_material_recovery_case_package.py',
               'tests/test_ingest_bounded_planar_external_nonlinear_material_recovery_results.py',
               'tests/test_build_bounded_planar_same_operator_supplemental_execution.py',
               'tests/test_build_bounded_planar_external_vv_matrix.py',
               'tests/test_build_bounded_planar_external_vv_matrix_from_operator_bundle.py',
               'docs/external-code-to-code-technical-execution.md',
               'docs/external-vv-independent-operator-intake.md',
               'docs/external-vv-level2-promotion-gate.md',
               'docs/bounded-planar-external-vv-matrix.md',
               'docs/opensees-calculix-current-source-workflow.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'vv.opensees_level2',
  'implemented': True,
  'interfaces': ['evidence'],
  'limitations': ['Pinned external comparison values and tracked receipts are historical inputs '
                  'only. Exact-current coverage, freshness, clean-runner parity, blockers, and '
                  'counts are authoritative only in the source-bound, attested Product State '
                  'Current CI artifact for the exact commit; the registry intentionally carries no '
                  'volatile coverage total. Missing or unverifiable exact-current evidence '
                  'receives no credit. Independent operator identity, project legal approvals, '
                  'complete scientific decisions, and a signed promotion decision remain absent. '
                  'The Level 2 gate remains blocked, external_vv_level stays 0, and no design, '
                  'commercial-equivalence, or release authority is granted.'],
  'numerical_authority': 'none',
  'profile': 'independent_operator_promotion_gate_v1',
  'public': False,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'runtime_artifacts': [{'path': 'artifacts/vv/bounded_planar_external_linear_case_package/manifest.json',
                         'producer': 'scripts/build_bounded_planar_external_linear_case_package.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-linear-case-package.v1'},
                        {'path': 'artifacts/vv/bounded_planar_external_negative_case_package/manifest.json',
                         'producer': 'scripts/build_bounded_planar_external_negative_case_package.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-negative-case-package.v1'},
                        {'path': 'artifacts/vv/bounded_planar_external_scaling_case_package/manifest.json',
                         'producer': 'scripts/build_bounded_planar_external_scaling_case_package.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-scaling-case-package.v1'},
                        {'path': 'artifacts/vv/bounded_planar_external_modal_buckling_case_package/manifest.json',
                         'producer': 'scripts/build_bounded_planar_external_modal_buckling_case_package.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-modal-buckling-case-package.v1'},
                        {'path': 'artifacts/vv/bounded_planar_external_nonlinear_material_recovery_case_package/manifest.json',
                         'producer': 'scripts/build_bounded_planar_external_nonlinear_material_recovery_case_package.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-nonlinear-material-recovery-case-package.v1'},
                        {'path': 'artifacts/vv/bounded_planar_same_operator_supplemental_execution/receipts/nonlinear-material-recovery-technical-receipt.json',
                         'producer': 'scripts/build_bounded_planar_same_operator_supplemental_execution.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-nonlinear-material-recovery-execution-receipt.v1'},
                        {'path': 'artifacts/vv/bounded_planar_same_operator_supplemental_execution/receipt.json',
                         'producer': 'scripts/build_bounded_planar_same_operator_supplemental_execution.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-same-operator-supplemental-execution.v1'},
                        {'path': 'artifacts/manifests/bounded_planar_external_vv_matrix.current.v1.json',
                         'producer': 'scripts/build_bounded_planar_external_vv_matrix.py',
                         'required_at': 'verification',
                         'schema_version': 'bounded-planar-external-vv-matrix-status.v1'}],
  'status': 'blocked',
  'title': 'OpenSees Level 2 verification'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/release_evidence/productization/external_modal_buckling_technical_execution_receipt.json',
               '.github/workflows/opensees-calculix-current-source.yml',
               'scripts/run_external_vv_clean_runner.sh',
               'scripts/run_external_modal_buckling_technical_receipt.py',
               'tests/test_external_modal_buckling_technical_receipt.py',
               'docs/external-code-to-code-technical-execution.md',
               'docs/opensees-calculix-current-source-workflow.md'],
  'executable': False,
  'external_vv_level': 0,
  'id': 'vv.second_solver_level2',
  'implemented': False,
  'interfaces': ['evidence'],
  'limitations': ['Tracked CalculiX and clean-runner receipts are historical inputs and never '
                  'establish current status. Exact-current same-operator execution and '
                  'cross-environment parity are credited only when an attested clean-runner '
                  'artifact for the exact commit is attached to the Product State Current '
                  'artifact; absent or invalid evidence fails closed. Independent operator '
                  'attestation, legal review, broader coverage, and second-solver Level 2 '
                  'promotion remain absent.'],
  'numerical_authority': 'none',
  'profile': 'independent_operator_promotion_required',
  'public': False,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'blocked',
  'title': 'Second independent solver Level 2 verification'},
 {'authority': 'bounded_source_bound_uniaxial_crack_band_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/concrete_damage.py',
               'src/structural_analysis/benchmark/fracture_energy_concrete.py',
               'src/structural_analysis/schemas/fracture_energy_concrete_mesh_objectivity_v1.schema.json',
               'artifacts/benchmarks/fracture_energy_concrete_mesh_objectivity.json',
               'scripts/build_fracture_energy_concrete_benchmark.py',
               'tests/test_fracture_energy_concrete.py',
               'docs/fracture-energy-concrete-mesh-objectivity.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'material.fracture_energy_concrete',
  'implemented': True,
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Source-bound mesh-objectivity evidence is limited to a seeded single-crack '
                  'uniaxial RC tie. Arbitrary frame or shell localization, multiaxial concrete, '
                  'confinement, bond slip, published or external validation, independent '
                  'engineering review, and release promotion remain open.'],
  'numerical_authority': 'bounded_source_bound_uniaxial_crack_band_candidate',
  'profile': 'localized_crack_band_rc_tie_2_4_8_meshes.v1',
  'public': False,
  'recovery_authority': 'bounded_source_bound_uniaxial_crack_band_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Fracture-energy concrete'},
 {'authority': 'bounded_repository_benchmark_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/benchmark/stateful_corotational_steel_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_concrete_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_composite_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_linked_frame_cyclic.py',
               'tests/test_stateful_corotational_steel_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_concrete_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_composite_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_linked_frame_cyclic_benchmark.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.cyclic_corotational_fiber_frames',
  'implemented': True,
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Repository-generated steel, concrete, composite, and link cases only; no '
                  'published cyclic acceptance, 3D response, or release authority.'],
  'numerical_authority': 'bounded_repository_benchmark_candidate',
  'profile': 'two_member_planar_material_state_commit_rollback.v1',
  'public': False,
  'recovery_authority': 'bounded_repository_benchmark_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Cyclic corotational fiber-frame benchmarks'},
 {'authority': 'consumer_only',
  'category': 'application',
  'evidence': ['docs/workbench-v2.md',
               'src/workbench-v2/model/jobProvider.ts',
               'tests/frontend/workbench-v2-e2e.spec.ts',
               'tests/frontend/workbench-v2-job-contract.spec.ts'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'app.workbench_result_evidence',
  'implemented': True,
  'interfaces': ['workbench'],
  'limitations': ['Durable-job publication is accepted only when raw artifact hashes, the complete '
                  'typed corotational engineering ResultIR shape and descriptor bundle, '
                  'unified-result bindings, authority axes, and the exact core validation report '
                  'all agree; legacy normalized result rows are not exposed by the durable reader.',
                  'Workbench display and review decisions never create solver truth.'],
  'numerical_authority': 'consumer_only',
  'profile': 'typed_workbench_case_evidence_and_result_ir_reader',
  'public': True,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'bounded_public',
  'title': 'Workbench result and evidence review'},
 {'authority': 'proposal_and_evaluation_only',
  'category': 'ai_control',
  'evidence': ['src/structural_analysis/ai/shadow_solver_controller.py',
               'docs/ai-shadow-solver-controller.md',
               'tests/test_shadow_solver_controller.py',
               'src/structural_analysis/ai/offline_counterfactual.py',
               'artifacts/ai/offline_counterfactual_dataset.json',
               'artifacts/ai/shadow_policy_scorecard.json',
               'docs/offline-counterfactual-shadow-scorecard.md',
               'tests/test_ai_offline_counterfactual.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'ai.solver_shadow_control',
  'implemented': True,
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Shadow proposals are not executed and cannot alter solver truth.',
                  'The checked-in scorecard is a repository contract fixture; v1 has no signed '
                  'independent-source attestation and guarded execution remains unavailable.'],
  'numerical_authority': 'proposal_and_evaluation_only',
  'profile': 'deterministic_baseline_plus_replay_bound_offline_scorecard.v1',
  'public': False,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'shadow_only',
  'title': 'AI solver shadow control'},
 {'authority': 'none',
  'category': 'ai_control',
  'evidence': ['docs/ai-shadow-solver-controller.md',
               'docs/offline-counterfactual-shadow-scorecard.md',
               'docs/structural-analysis-ai-engine-gap-ledger.md'],
  'executable': False,
  'external_vv_level': 0,
  'id': 'ai.guarded_execution',
  'implemented': False,
  'interfaces': ['internal_python'],
  'limitations': ['No production action execution or autonomous engineering authority.',
                  'A repository-generated contract fixture cannot satisfy independent policy or '
                  'guard evidence.'],
  'numerical_authority': 'none',
  'profile': 'offline_counterfactual_and_guard_receipts_required',
  'public': False,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'blocked',
  'title': 'Guarded AI execution'},
 {'authority': 'none',
  'category': 'backend',
  'evidence': ['docs/engine-v2-cpu-hip-fgmres-recurrence.md',
               'implementation/phase1/release_evidence/productization/engine_v2_cpu_hip_fgmres_recurrence_receipt.json',
               'implementation/phase1/release_evidence/productization/engine_v2_hip_fgmres_stage4_status.json',
               'tests/test_engine_v2_hip_fgmres_stage4_status.py'],
  'executable': False,
  'external_vv_level': 0,
  'id': 'backend.rocm_hip_production',
  'implemented': False,
  'interfaces': ['hardware_runner'],
  'limitations': ['Residency, full-path parity, fallback, and hardware provenance gates remain '
                  'open.'],
  'numerical_authority': 'none',
  'profile': 'performance_track_after_cpu_sparse_and_external_vv',
  'public': False,
  'recovery_authority': 'not_applicable',
  'release_eligible': False,
  'representable': True,
  'status': 'blocked',
  'title': 'ROCm/HIP production backend'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/corotational_frame2d_member_features.py',
               'src/structural_analysis/api/nonlinear_frame.py',
               'tests/test_corotational_frame2d_member_features.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'examples/bounded_planar_frame_alpha.model-ir.v2.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'docs/external-code-to-code-technical-execution.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame2d.rigid_offset',
  'implementation_ref': 'ed7ea935f0318ba5102edd7f2a197a7beaf013f7',
  'implemented': True,
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['Bounded connected planar Frame2D candidate only.',
                  'Stored same-operator OpenSees values still pass current-product replay for the '
                  'combined member-feature sample, but a current-source external runtime rerun is '
                  'missing.',
                  'No independent Level 2/3 V&V, design authority, or release eligibility.'],
  'merged_pr': 227,
  'numerical_authority': 'bounded_candidate',
  'profile': 'connected_planar_frame2d_finite_rigid_offset_candidate.v1',
  'public': False,
  'recovery_authority': 'exact_bounded_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Frame2D finite rigid offset'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/corotational_frame2d_member_features.py',
               'src/structural_analysis/api/nonlinear_frame.py',
               'tests/test_corotational_frame2d_member_features.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'examples/bounded_planar_frame_alpha.model-ir.v2.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'docs/external-code-to-code-technical-execution.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame2d.release.rz',
  'implementation_ref': 'ed7ea935f0318ba5102edd7f2a197a7beaf013f7',
  'implemented': True,
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['RZ-only bounded release with same-parent local equilibrium and Schur '
                  'condensation.',
                  'Stored same-operator OpenSees values still pass current-product replay for the '
                  'combined member-feature sample, but a current-source external runtime rerun is '
                  'missing.',
                  'No broader release family or release promotion.'],
  'merged_pr': 227,
  'numerical_authority': 'bounded_candidate',
  'profile': 'connected_planar_frame2d_rz_end_release_candidate.v1',
  'public': False,
  'recovery_authority': 'exact_bounded_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Frame2D RZ end release'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/corotational_frame2d_member_features.py',
               'src/structural_analysis/api/nonlinear_frame.py',
               'tests/test_corotational_frame2d_member_features.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'examples/bounded_planar_frame_alpha.model-ir.v2.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'docs/external-code-to-code-technical-execution.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame2d.uniform_member_load',
  'implementation_ref': 'ed7ea935f0318ba5102edd7f2a197a7beaf013f7',
  'implemented': True,
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['Uniform dead load in the initial member-local axis only.',
                  'Stored same-operator OpenSees values still pass current-product replay for the '
                  'combined member-feature sample, but a current-source external runtime rerun is '
                  'missing.',
                  'No general distributed, follower, thermal, or moving member load authority.'],
  'merged_pr': 227,
  'numerical_authority': 'bounded_candidate',
  'profile': 'connected_planar_frame2d_uniform_dead_load_candidate.v1',
  'public': False,
  'recovery_authority': 'exact_bounded_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Frame2D uniform member dead load'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/adapters/bounded_planar_model_ir.py',
               'src/structural_analysis/api/nonlinear_frame.py',
               'tests/test_bounded_planar_model_ir_adapter.py',
               'tests/test_external_code_to_code_technical_receipt.py',
               'examples/bounded_planar_settlement.model-ir.v2.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'docs/corotational-connected-frame2d.md',
               'docs/external-code-to-code-technical-execution.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame2d.prescribed_support_displacement',
  'implemented': True,
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['Constrained UX, UY, or RZ terminal values are proportional to the load factor; '
                  'this is distinct from direct displacement control of a free DOF.',
                  'The iterative settlement comparison requires an explicit nonzero free-equation '
                  'reference load so EquationScaling remains evidence-backed; prescribed-only '
                  'free-equation paths fail closed.',
                  'Stored same-operator host and container OpenSees values still pass '
                  'current-product replay for one -0.1 mm settlement case, but the current-source '
                  'external runtime rerun, independent Level 2/3 V&V, design authority, and '
                  'release eligibility remain absent.'],
  'numerical_authority': 'bounded_candidate',
  'profile': 'bounded_planar_frame2d_proportional_prescribed_support_candidate.v1',
  'public': False,
  'recovery_authority': 'exact_bounded_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Frame2D prescribed support displacement'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_displacement_control.py',
               'tests/test_stateful_corotational_fiber_frame2d_displacement_control.py'],
  'executable': True,
  'external_vv_level': 0,
  'hardening_ref': 'da87ef0221705b9483a0b239e151495b66244011',
  'id': 'frame2d.direct_displacement_control',
  'implementation_ref': '91e00a57db8fae1b2975c291f4439acdb75879ae',
  'implemented': True,
  'interfaces': ['internal_python'],
  'limitations': ['Internal dense augmented-Newton path with one free UX/UY control DOF.',
                  'Unified public J1-J5 exposure, native sparse execution, and external V&V remain '
                  'open.'],
  'merged_pr': 197,
  'numerical_authority': 'bounded_candidate',
  'profile': 'single_control_dof_dense_augmented_newton_candidate.v1',
  'public': False,
  'recovery_authority': 'source_authenticated_checkpoint_replay_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Frame2D direct displacement control'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['docs/p2-frame3d-global-load-path.md',
               'src/structural_analysis/assembly/corotational_frame3d_global.py',
               'src/structural_analysis/solvers/equation_scaling_6dof.py',
               'src/structural_analysis/elements/corotational_frame3d.py',
               'tests/test_corotational_frame3d_global.py',
               'tests/test_corotational_frame3d_scalable_graph.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame3d.corotational',
  'implementation_ref': '74f1c7d9d9c9611d74752acaf57684e1ba4799a9',
  'implemented': True,
  'interfaces': ['internal_python'],
  'limitations': ['Bounded internal 3D graph candidate; the dense load-control solve uses shared '
                  'source-bound 6DOF force/moment scaling with fail-closed real-binary64 source '
                  'validation, residual-and-increment commit gates, strict '
                  'scaled-residual-decreasing backtracking, final equilibrium reassembly, and '
                  'parent-checkpoint immutability checks.',
                  'No independent external 3D comparison or release authority.'],
  'merged_pr': 231,
  'numerical_authority': 'bounded_candidate',
  'profile': 'bounded_global_corotational_frame3d_graph_candidate.v1',
  'public': False,
  'recovery_authority': 'bounded_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Global corotational Frame3D'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/elements/stateful_corotational_fiber_frame3d.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_sparse_checkpoint_v1.schema.json',
               'tests/test_stateful_corotational_fiber_frame3d.py',
               'tests/test_stateful_corotational_frame3d_sparse.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame3d.stateful_fiber',
  'implementation_ref': 'b5d530bd4377e9eee4771e3b2df50c3ffc316ed4',
  'implemented': True,
  'interfaces': ['internal_python'],
  'limitations': ['Two- or three-point axial-biaxial fiber integration over a bounded Timoshenko '
                  'reference; native sparse load control uses model-bound 6DOF force/moment '
                  'scaling, residual-and-increment commit gates, strict residual-decreasing '
                  'backtracking, exact material-response accepted-parent hash binding, '
                  'material-specific steel/concrete/bond-slip admissibility through nested states, '
                  'binary64-exact checkpoint displacement identity, deterministic unloaded genesis '
                  'plus non-genesis nonzero-parent invariants, checkpoint-displacement '
                  'material-state replay, final equilibrium reassembly, fail-closed scaled '
                  'factorization diagnostics, and explicitly convergence-classified adaptive load '
                  'cutback with rejected-trial rollback and exact accepted-checkpoint resume. A '
                  'zero-update child is valid only when a changed load acts on restrained '
                  'equations and every replay, factorization, reassembly, and equilibrium gate '
                  'passes.',
                  'Shear and torsion remain elastic; the separately registered '
                  'direct-displacement-control candidate does not add arc-length, analytic 3D '
                  'tangents, independent external 3D V&V, or release authority.'],
  'merged_pr': 237,
  'numerical_authority': 'bounded_candidate',
  'profile': 'bounded_stateful_corotational_fiber_frame3d_candidate.v1',
  'public': False,
  'recovery_authority': 'state_checkpoint_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Stateful corotational fiber Frame3D'},
 {'authority': 'bounded_candidate',
  'category': 'analysis',
  'evidence': ['docs/p2-frame3d-direct-displacement-control.md',
               'examples/bounded_frame3d_direct_control.model-ir.v2.json',
               'examples/bounded_frame3d_direct_control_axial_yield.model-ir.v2.json',
               'examples/bounded_frame3d_direct_control_torsion.model-ir.v2.json',
               'examples/bounded_frame3d_direct_control_ry_bending.model-ir.v2.json',
               'examples/bounded_frame3d_direct_control_rz_bending.model-ir.v2.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'src/structural_analysis/adapters/bounded_frame3d_direct_control_model_ir.py',
               'src/structural_analysis/api/frame3d_direct_control.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_displacement_control.py',
               'src/structural_analysis/schemas/bounded_frame3d_direct_control_checkpoint_v1.schema.json',
               'src/structural_analysis/schemas/bounded_frame3d_direct_control_checkpoint_v2.schema.json',
               'src/structural_analysis/schemas/bounded_frame3d_direct_control_result_v1.schema.json',
               'src/structural_analysis/schemas/bounded_frame3d_direct_control_result_v2.schema.json',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_displacement_control_resume_binding_v1.schema.json',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_displacement_control_resume_binding_v2.schema.json',
               'tests/test_bounded_frame3d_direct_control_api.py',
               'tests/test_stateful_corotational_frame3d_displacement_control.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'frame3d.direct_displacement_control',
  'implemented': True,
  'interfaces': ['internal_python', 'candidate_model_ir_v2_python_api'],
  'limitations': ['One free UX, UY, UZ, RX, RY, or RZ coordinate and one proportional '
                  'reference-load factor are solved by a source-scaled sparse augmented Newton '
                  'path with residual, increment, control, line-search, material-admissibility, '
                  'final-reassembly, and factorization gates. Finite but constitutively '
                  'unreachable bilinear-steel checkpoint states and target increments already '
                  'inside the configured control tolerance fail before solving. Bounded adaptive '
                  'target cutback retries only maximum-iteration or pure admissible '
                  'merit-line-search failures, uses unit-specific minima plus '
                  'depth/substep/whole-path attempt bounds, and hash-records every rejected target '
                  'against an immutable accepted parent.',
                  'The direct-control Newton budget cannot exceed the sparse Frame3D budget bound '
                  'into accepted checkpoints. Checkpoint converged_iterations counts applied '
                  'Newton/line-search updates rather than the terminal gate-evaluation row, so '
                  'bound-edge convergence remains self-validating. Terminal increment, '
                  'load-increment, and condition scalars are unavailable when the terminal '
                  'factorization fails; earlier successful diagnostics remain history only.',
                  'The bounded_frame3d_direct_displacement_control ModelIR v2 profile and '
                  'candidate Python API expose source-bound zero-offset/unreleased graphs, '
                  'binary64-exact projected coordinates/properties/loads, explicit bilinear '
                  'steel/shear modulus, free-equation reference loads, ordered '
                  'node/member/material recovery, and exact-resume artifacts while keeping '
                  'capability-registry public=false. Persisted checkpoints require a deterministic '
                  'unloaded genesis plus non-genesis nonzero-parent invariants, complete ordered '
                  'recovery identities, finite repository-canonical JSON bytes, and raw-to-typed '
                  'checkpoint/resume-binding/top-level-envelope numeric identity. A zero-update '
                  'child is permitted only for a changed load confined to restrained equations '
                  'after all replay, factorization, reassembly, and equilibrium gates pass. '
                  'Default monotonic paths retain the v1 direction binding; opt-in reversal is '
                  'limited to exact bilinear combined-hardening steel and uses a v2 '
                  'last-leg/cumulative-count/rolling-target-chain binding whose completed-target '
                  'count cannot exceed the accepted step index. The unsigned hashes provide '
                  'internal consistency, not authentication against complete rehashing. '
                  'Same-operator OpenSees 3D forceBeamColumn comparisons cover one monotonic '
                  'axial-yield UX path, one five-target axial reversal path against the exact '
                  'Hardening law, and pure-axis elastic RX, RY, and RZ paths. Coupled MY+MZ '
                  'probing exposes formulation-dependent second-order torsional coupling and is '
                  'not promoted; other cyclic histories/materials, coupled multi-axis or '
                  'multi-control behavior, general material/shear/torsion coupling, and '
                  'independent V&V remain open. A bare internal checkpoint is an unbound restart '
                  'and an incomplete intermediate cutback checkpoint is not exact continuation. '
                  'Prescribed supports, offsets/releases, arc-length continuation, Workbench '
                  'execution, independent direct-control 3D V&V, design authority, and release '
                  'authority remain unsupported.'],
  'numerical_authority': 'bounded_candidate',
  'profile': 'stateful_corotational_frame3d_sparse_direct_displacement_control.v1',
  'public': False,
  'recovery_authority': 'state_checkpoint_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Frame3D direct displacement control'},
 {'authority': 'constitutive_candidate',
  'category': 'material',
  'evidence': ['docs/p2-material-candidates.md',
               'src/structural_analysis/materials/confined_concrete.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'tests/test_p2_material_candidates.py',
               'tests/test_stateful_corotational_frame3d_materials.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'material.confined_concrete',
  'implementation_ref': '12c9bfbc1106cb82fc2d161a0596d91a8583f7d9',
  'implemented': True,
  'interfaces': ['internal_python'],
  'limitations': ['Monotonic uniaxial compression envelope only. Stateful unloading, reversal, '
                  'tension, and cyclic trials fail closed with unsupported_constitutive_path.',
                  'Ultimate-strain exceedance emits confined_concrete_crushing_event instead of '
                  'silently entering the discontinuous residual cutoff in solver execution.',
                  'Multiaxial behavior, localization regularization, published calibration, and '
                  'release authority remain unsupported.'],
  'merged_pr': 235,
  'numerical_authority': 'constitutive_candidate',
  'profile': 'mander_uniaxial_monotonic_compression.v1',
  'public': False,
  'recovery_authority': 'state_lineage_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Mander monotonic confined concrete'},
 {'authority': 'constitutive_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/bond_slip.py',
               'tests/test_bond_slip_interface.py',
               'tests/test_p2_material_candidates.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'material.bond_slip',
  'implementation_ref': '12c9bfbc1106cb82fc2d161a0596d91a8583f7d9',
  'implemented': True,
  'interfaces': ['internal_python'],
  'limitations': ['Bounded SI-unit connector material point.',
                  'Connector groups, published calibration, independent V&V, and release authority '
                  'remain open.'],
  'merged_pr': 235,
  'numerical_authority': 'constitutive_candidate',
  'profile': 'bounded_cyclic_bond_slip_material_point.v1',
  'public': False,
  'recovery_authority': 'state_lineage_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Cyclic bond-slip connector'},
 {'authority': 'constitutive_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/partial_composite.py',
               'src/structural_analysis/elements/stateful_corotational_partial_composite_frame3d.py',
               'tests/test_p2_material_candidates.py',
               'tests/test_stateful_corotational_partial_composite_frame3d.py'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'material.partial_composite',
  'implementation_ref': '12c9bfbc1106cb82fc2d161a0596d91a8583f7d9',
  'implemented': True,
  'integration_ref': 'b5d530bd4377e9eee4771e3b2df50c3ffc316ed4',
  'interfaces': ['internal_python'],
  'limitations': ['Condensed single-slip-mode axial member coupling.',
                  'General shear lag, uplift/contact, connector groups, and external V&V remain '
                  'open.'],
  'merged_pr': 235,
  'numerical_authority': 'constitutive_candidate',
  'profile': 'condensed_single_slip_partial_composite_candidate.v1',
  'public': False,
  'recovery_authority': 'state_lineage_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Steel-concrete partial composite interaction'},
 {'authority': 'bounded_reference_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/solvers/nonlinear/transient.py',
               'src/structural_analysis/schemas/nonlinear_transient_checkpoint_v1.schema.json',
               'src/structural_analysis/schemas/nonlinear_transient_checkpoint_chain_v1.schema.json',
               'tests/test_nonlinear_transient.py',
               'docs/nonlinear-transient-reference.md'],
  'executable': True,
  'external_vv_level': 0,
  'id': 'analysis.nonlinear_transient_sdof',
  'implementation_ref': '698aec6cffa9d4efab5eb8b7c332f9ba6a529c6d',
  'implemented': True,
  'interfaces': ['internal_python'],
  'limitations': ['Fail-closed Newmark average-acceleration bilinear SDOF reference kernel.',
                  'Detached checkpoints have self-consistency authority only; resume requires a '
                  'genesis-rooted source-authenticated force-history chain with full Newmark and '
                  'work/dissipation replay.',
                  'MDOF nonlinear dynamics, general hysteretic materials, external V&V, and '
                  'release authority remain open.'],
  'merged_pr': 233,
  'numerical_authority': 'bounded_reference_candidate',
  'profile': 'newmark_average_acceleration_bilinear_sdof_reference.v1',
  'public': False,
  'recovery_authority': 'checkpoint_replay_candidate',
  'release_eligible': False,
  'representable': True,
  'status': 'experimental',
  'title': 'Nonlinear transient SDOF'})

def capabilities(*, public_only: bool = False) -> tuple[dict[str, Any], ...]:
    rows = CAPABILITY_ROWS
    if public_only:
        rows = tuple(row for row in rows if row['public'])
    return tuple(deepcopy(row) for row in rows)
