"""Generated capability registry. Do not edit directly."""

from __future__ import annotations

from typing import Any

CAPABILITY_SCHEMA_VERSION = 'structural-analysis-capabilities.v1'
CAPABILITY_AUTHORITY_RULES: dict[str, Any] = {'ai_truth_owner': 'none',
 'fallback_promotion_allowed': False,
 'gpu_track': 'performance_after_cpu_sparse_reference_and_external_vv',
 'solver_truth_owner': 'structural_analysis_core',
 'workbench_truth_owner': 'none'}
CAPABILITY_ROWS: tuple[dict[str, Any], ...] = ({'authority': 'validated_input_contract',
  'category': 'model_io',
  'evidence': ['tests/test_structural_analysis_core_api.py'],
  'id': 'model.neutral_canonical',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Only schema-declared entities and units are accepted.'],
  'profile': 'structural-analysis-canonical-model.v1',
  'public': True,
  'status': 'supported',
  'title': 'Neutral canonical model'},
 {'authority': 'input_translation_with_provenance',
  'category': 'model_io',
  'evidence': ['src/structural_analysis/io/midas/loader.py',
               'tests/test_structural_analysis_core_api.py'],
  'id': 'io.midas_mgt',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Unsupported records remain explicit; exact native round-trip is not closed.'],
  'profile': 'topology_and_supported_property_subset',
  'public': True,
  'status': 'bounded_public',
  'title': 'MIDAS MGT import'},
 {'authority': 'entity_scan_and_model_health_only',
  'category': 'model_io',
  'evidence': ['src/structural_analysis/io/ifc/loader.py',
               'tests/test_structural_analysis_core_api.py'],
  'id': 'io.ifc_model_health',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Not a general analysis-ready IFC structural-model compiler.'],
  'profile': 'ifc_step_model_health',
  'public': True,
  'status': 'bounded_public',
  'title': 'IFC model-health import'},
 {'authority': 'numerical_and_engineering_within_supported_elements',
  'category': 'analysis',
  'evidence': ['docs/authoritative-cpu-linear-solver.md',
               'tests/test_structural_analysis_core_api.py'],
  'id': 'analysis.linear_static',
  'interfaces': ['python_api', 'cli', 'workbench'],
  'limitations': ['No general shell, contact, staged-construction, or design-code authority.'],
  'profile': 'cpu_dense_or_scipy_sparse_supported_frame_truss',
  'public': True,
  'status': 'bounded_public',
  'title': 'Linear static analysis'},
 {'authority': 'numerical_within_explicit_frame_truss_mass_profile',
  'category': 'analysis',
  'evidence': ['docs/phase2-whole-model-modal-analysis.md',
               'tests/test_whole_model_modal_analysis.py'],
  'id': 'analysis.modal',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The public default is dense; the opt-in sparse extractor is experimental, still '
                  'uses dense whole-model assembly, and has no independent Level 2 comparison.'],
  'profile': 'dense_symmetric_generalized_eigen_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Whole-model modal analysis'},
 {'authority': 'numerical_within_explicit_preload_profile',
  'category': 'analysis',
  'evidence': ['docs/phase2-whole-model-linear-buckling.md',
               'tests/test_whole_model_buckling_analysis.py'],
  'id': 'analysis.linear_buckling',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The public default is dense; the opt-in sparse reciprocal extractor is '
                  'experimental, still uses dense whole-model assembly, and has no independent '
                  'Level 2 comparison.'],
  'profile': 'dense_symmetric_generalized_eigen_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Whole-model linear buckling'},
 {'authority': 'bounded_material_geometric_newton',
  'category': 'analysis',
  'evidence': ['docs/public-two-bar-nonlinear-truss.md',
               'src/structural_analysis/api/nonlinear_truss.py'],
  'id': 'analysis.nonlinear_two_bar_truss',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The profile does not generalize to arbitrary truss or frame topology.'],
  'profile': 'symmetric_two_bar_material_geometric_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Nonlinear two-bar truss'},
 {'authority': 'exact_reaction_member_section_fiber_recovery',
  'category': 'analysis',
  'evidence': ['docs/public-rc-fiber-frame.md', 'tests/test_public_rc_fiber_frame_api.py'],
  'id': 'analysis.nonlinear_rc_fiber_frame_fixed_chord',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Serial cantilever only; zero prescribed movement; dense CPU load control.'],
  'profile': 'planar_serial_cantilever_explicit_rectangular_rc.v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Fixed-chord RC fiber frame'},
 {'authority': 'bounded_j1_j5_and_exact_engineering_recovery_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/api/nonlinear_frame.py',
               'src/structural_analysis/assembly/corotational_frame2d_member_features.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_displacement_control.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_engineering_recovery.py',
               'tests/test_corotational_fiber_frame_displacement_control.py',
               'tests/test_corotational_frame2d_member_features.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'docs/corotational-member-features.md',
               'docs/unified-nonlinear-frame-api.md'],
  'id': 'analysis.nonlinear_corotational_fiber_frame_2d',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Load control and direct single-DOF displacement control, RZ end releases, '
                  'global-XY rigid offsets, and uniform initial-local-axis dead loads are bound; '
                  'both Level 2 slots and release promotion remain open.'],
  'profile': 'corotational_one_bay_portal.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Corotational 2D fiber frame'},
 {'authority': 'bounded_native_coo_csr_and_fail_closed_exact_conditioning_candidate',
  'category': 'backend',
  'evidence': ['src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_sparse.py',
               'src/structural_analysis/assembly/corotational_frame3d_graph.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/solvers/nonlinear/sparse_factorization.py',
               'src/structural_analysis/solvers/nonlinear/scalable_sparse_factorization.py',
               'src/structural_analysis/schemas/scalable_sparse_factorization_diagnostic_v1.schema.json',
               'tests/test_corotational_fiber_frame_sparse.py',
               'tests/test_sparse_factorization_diagnostics.py',
               'tests/test_scalable_sparse_factorization.py',
               'tests/test_corotational_frame3d_scalable_graph.py',
               'docs/sparse-factorization-conditioning-diagnostics.md'],
  'id': 'backend.nonlinear_sparse',
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['The public exact-conditioning path remains bounded to 256 equations. A separate '
                  'CPU-only blockwise exact diagnostic is bounded to 1536 equations and is wired '
                  'only into the experimental stateful 3D graph path; an actual 258-free-equation '
                  'frame passes. Its exact inverse-column diagnostic still has quadratic work and '
                  'does not close production-scale policy, performance/memory evidence, external '
                  'V&V, or release promotion.'],
  'profile': 'corotational_element_triplet_coalesce_sorted_csr_fp64_plus_blocked_exact_1536.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Native sparse nonlinear backend'},
 {'authority': 'bounded_sparse_low_mode_extraction_candidate',
  'category': 'backend',
  'evidence': ['src/structural_analysis/solvers/sparse_generalized_eigen.py',
               'tests/test_sparse_generalized_eigen.py',
               'tests/test_whole_model_modal_analysis.py',
               'tests/test_whole_model_buckling_analysis.py',
               'docs/sparse-modal-buckling.md'],
  'id': 'backend.sparse_modal_buckling',
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['Whole-model assembly remains dense; binary mode artifacts, production-scale '
                  'conditioning, independent Level 2 V&V, and release promotion are open.'],
  'profile': 'arpack_modal_and_superlu_reciprocal_buckling.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Sparse modal and buckling extraction'},
 {'authority': 'bounded_algorithm_and_checkpoint_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/solvers/nonlinear/transient.py',
               'src/structural_analysis/schemas/nonlinear_transient_checkpoint_v1.schema.json',
               'tests/test_nonlinear_transient.py',
               'docs/nonlinear-transient-reference.md'],
  'id': 'analysis.nonlinear_transient_sdof',
  'interfaces': ['internal_python'],
  'limitations': ['One force-driven DOF only; no frame assembly, base excitation, adaptive '
                  'stepping, published validation, or release authority.'],
  'profile': 'newmark_average_acceleration_bilinear_sdof.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Nonlinear transient SDOF reference'},
 {'authority': 'bounded_exact_engineering_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_general.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_displacement_control.py',
               'src/structural_analysis/assembly/corotational_frame2d_member_features.py',
               'tests/test_corotational_fiber_frame_displacement_control.py',
               'tests/test_corotational_fiber_frame_general.py',
               'tests/test_corotational_frame2d_member_features.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'docs/corotational-connected-frame2d.md',
               'docs/corotational-member-features.md'],
  'id': 'analysis.nonlinear_corotational_connected_frame2d',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Connected simple graph only; load control or direct single-DOF displacement '
                  'control is supported; prescribed support histories remain proportional to '
                  'solved load factor; member loads are uniform initial-local-axis dead loads; '
                  'both Level 2 slots remain open.'],
  'profile': 'corotational_connected_frame2d.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Connected corotational 2D fiber frame'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'implementation/phase1/release_evidence/productization/external_modal_buckling_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'benchmarks/clean-runners/opensees-calculix/Dockerfile',
               'benchmarks/clean-runners/opensees-calculix/run_clean_runner.py',
               'scripts/run_external_code_to_code_technical_receipt.py',
               'scripts/run_external_modal_buckling_technical_receipt.py',
               'scripts/run_external_vv_clean_runner.sh',
               'tests/test_external_code_to_code_technical_receipt.py',
               'tests/test_external_modal_buckling_technical_receipt.py',
               'tests/test_external_vv_clean_runner_contract.py',
               'docs/external-code-to-code-technical-execution.md'],
  'id': 'vv.opensees_level2',
  'interfaces': ['evidence'],
  'limitations': ['Fresh pinned OpenSees technical executions and a '
                  'read-only-source/network-disabled same-operator container reproduction pass '
                  'narrow modal, consistent-mass modal/MAC, linear-static, and fixed two-element '
                  'elastic spatial-frame comparisons, but independent operator attestation, public '
                  'corotational nonlinear breadth, Level 2 normalization, review, and promotion '
                  'receipt are absent.'],
  'profile': 'clean_runner_required',
  'public': False,
  'status': 'blocked',
  'title': 'OpenSees Level 2 verification'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'implementation/phase1/release_evidence/productization/external_modal_buckling_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'benchmarks/clean-runners/opensees-calculix/Dockerfile',
               'benchmarks/clean-runners/opensees-calculix/run_clean_runner.py',
               'scripts/run_external_code_to_code_technical_receipt.py',
               'scripts/run_external_modal_buckling_technical_receipt.py',
               'scripts/run_external_vv_clean_runner.sh',
               'tests/test_external_code_to_code_technical_receipt.py',
               'tests/test_external_modal_buckling_technical_receipt.py',
               'tests/test_external_vv_clean_runner_contract.py',
               'docs/external-code-to-code-technical-execution.md'],
  'id': 'vv.second_solver_level2',
  'interfaces': ['evidence'],
  'limitations': ['Fresh pinned CalculiX technical executions and a '
                  'read-only-source/network-disabled same-operator container reproduction pass '
                  'narrow axial-member and whole-model repeated-mode linear-buckling/subspace '
                  'comparisons, but independent operator attestation, broader frame/nonlinear '
                  'coverage, review, and a promoted second-solver Level 2 package are absent.'],
  'profile': 'independent_clean_runner_required',
  'public': False,
  'status': 'blocked',
  'title': 'Second independent solver Level 2 verification'},
 {'authority': 'bounded_uniaxial_crack_band_mesh_objectivity_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/concrete_damage.py',
               'src/structural_analysis/benchmark/fracture_energy_concrete.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'artifacts/benchmarks/fracture_energy_concrete_mesh_objectivity.json',
               'tests/test_fracture_energy_concrete.py',
               'tests/test_stateful_corotational_frame3d_materials.py',
               'docs/fracture-energy-concrete-mesh-objectivity.md',
               'docs/p2-frame3d-candidates.md'],
  'id': 'material.fracture_energy_concrete',
  'interfaces': ['internal_python'],
  'limitations': ['Mesh-objectivity evidence remains limited to the seeded single-crack uniaxial '
                  'RC tie. The same law is accepted by the experimental 3D member axial adapter, '
                  'but arbitrary frame/shell localization, multiaxial concrete, confinement, bond '
                  'slip, published validation, and release promotion remain open.'],
  'profile': 'localized_crack_band_rc_tie_2_4_8_meshes.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Fracture-energy concrete'},
 {'authority': 'bounded_material_point_and_axial_member_checkpoint_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/confined_concrete.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_sparse_checkpoint_v1.schema.json',
               'tests/test_p2_material_candidates.py',
               'tests/test_stateful_corotational_frame3d_materials.py',
               'docs/p2-material-candidates.md',
               'docs/p2-frame3d-candidates.md'],
  'id': 'material.confined_concrete',
  'interfaces': ['internal_python'],
  'limitations': ['The native-sparse 3D adapter adds immutable current/max-compression lineage but '
                  'no unloading law. Cyclic confined-concrete behavior, distributed fibers, '
                  'multiaxial response, localization, published calibration, and design authority '
                  'remain open.'],
  'profile': 'mander_uniaxial_monotonic_compression.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Uniaxial confined concrete'},
 {'authority': 'bounded_material_point_single_mode_and_distributed_two_layer_member_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/bond_slip.py',
               'src/structural_analysis/materials/partial_composite.py',
               'src/structural_analysis/elements/stateful_corotational_partial_composite_frame3d.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_sparse_checkpoint_v1.schema.json',
               'tests/test_p2_material_candidates.py',
               'tests/test_stateful_corotational_frame3d_materials.py',
               'tests/test_stateful_corotational_partial_composite_frame3d.py',
               'docs/p2-material-candidates.md',
               'docs/p2-frame3d-candidates.md'],
  'id': 'material.bond_slip_cyclic',
  'interfaces': ['internal_python'],
  'limitations': ['The 3D axial adapter statically condenses one connector coordinate; a separate '
                  'two-layer fiber member integrates cyclic connector points at two/three Gauss '
                  'stations and condenses a linear two-node slip field. General anchorage, shear '
                  'lag, uplift/contact, connector groups, published cyclic validation, and design '
                  'authority remain open.'],
  'profile': 'piecewise_softening_cyclic_connector.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Cyclic bond-slip connector'},
 {'authority': 'bounded_material_point_single_mode_axial_and_distributed_two_layer_fiber_member_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/partial_composite.py',
               'src/structural_analysis/elements/stateful_corotational_partial_composite_frame3d.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_sparse_checkpoint_v1.schema.json',
               'tests/test_p2_material_candidates.py',
               'tests/test_stateful_corotational_frame3d_materials.py',
               'tests/test_stateful_corotational_partial_composite_frame3d.py',
               'docs/p2-material-candidates.md',
               'docs/p2-frame3d-candidates.md'],
  'id': 'material.partial_composite_interaction',
  'interfaces': ['internal_python'],
  'limitations': ['One axial adapter condenses a single slip coordinate. The separate distributed '
                  'candidate couples two axial-biaxial fiber layers to a linear two-node slip '
                  'field and connector quadrature, but it is not a general '
                  'shear-lag/uplift/contact, effective-width, connector-group, published '
                  'validation, production-scale, or design-authority formulation.'],
  'profile': 'axial_two_layer_discrete_connector.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Partial composite interaction material point'},
 {'authority': 'bounded_same_parent_section_and_distributed_member_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/stateful_biaxial_fiber_section.py',
               'src/structural_analysis/elements/stateful_corotational_fiber_frame3d.py',
               'src/structural_analysis/elements/stateful_corotational_partial_composite_frame3d.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_sparse_checkpoint_v1.schema.json',
               'tests/test_stateful_biaxial_fiber_section.py',
               'tests/test_stateful_corotational_fiber_frame3d.py',
               'tests/test_stateful_corotational_partial_composite_frame3d.py',
               'docs/p2-material-candidates.md',
               'docs/p2-frame3d-candidates.md'],
  'id': 'material.stateful_biaxial_fiber_section',
  'interfaces': ['internal_python'],
  'limitations': ['Two/three-point 3D member integration is verified with numerical basic-mode '
                  'derivatives. A separate two-layer member adds condensed connector quadrature; '
                  'shear/torsion material coupling, general shear lag/uplift/contact, cyclic '
                  'confinement, multiaxial concrete, production-scale material behavior, published '
                  'validation, and design authority remain open.'],
  'profile': 'plane_section_axial_biaxial_discrete_fibers.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Stateful axial-biaxial fiber section'},
 {'authority': 'bounded_dense_elastic_native_sparse_distributed_biaxial_fiber_and_partial_composite_verification_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/elements/corotational_frame3d.py',
               'src/structural_analysis/elements/stateful_corotational_fiber_frame3d.py',
               'src/structural_analysis/elements/stateful_corotational_partial_composite_frame3d.py',
               'src/structural_analysis/materials/stateful_biaxial_fiber_section.py',
               'src/structural_analysis/assembly/corotational_frame3d_global.py',
               'src/structural_analysis/assembly/corotational_frame3d_graph.py',
               'src/structural_analysis/assembly/stateful_corotational_frame3d_sparse.py',
               'src/structural_analysis/solvers/nonlinear/scalable_sparse_factorization.py',
               'src/structural_analysis/schemas/corotational_frame3d_global_checkpoint_v1.schema.json',
               'src/structural_analysis/schemas/stateful_corotational_frame3d_sparse_checkpoint_v1.schema.json',
               'src/structural_analysis/schemas/scalable_sparse_factorization_diagnostic_v1.schema.json',
               'implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'scripts/run_external_code_to_code_technical_receipt.py',
               'tests/test_p2_frame3d_candidates.py',
               'tests/test_corotational_frame3d_global.py',
               'tests/test_stateful_corotational_frame3d_sparse.py',
               'tests/test_stateful_corotational_frame3d_materials.py',
               'tests/test_stateful_biaxial_fiber_section.py',
               'tests/test_stateful_corotational_fiber_frame3d.py',
               'tests/test_stateful_corotational_partial_composite_frame3d.py',
               'tests/test_corotational_frame3d_scalable_graph.py',
               'tests/test_scalable_sparse_factorization.py',
               'tests/test_external_code_to_code_technical_receipt.py',
               'tests/test_external_vv_clean_runner_contract.py',
               'docs/p2-frame3d-candidates.md',
               'docs/sparse-factorization-conditioning-diagnostics.md',
               'docs/external-code-to-code-technical-execution.md'],
  'id': 'analysis.corotational_frame_3d',
  'interfaces': ['internal_python'],
  'limitations': ['The dense elastic reference remains bounded to 16 nodes, 32 members, and 60 '
                  'free equations. The separate native-sparse graph is bounded to 128 nodes, 256 '
                  'members, and 768 free equations; a 44-node/43-member, 258-free-equation solve '
                  'is verified with blocked exact conditioning. Native COO/CSR, six axial '
                  'constitutive contracts, a two/three-point axial-biaxial fiber correction, and a '
                  'two-layer member with connector quadrature and a condensed linear slip field '
                  'verify reversal, commit/rollback, exact checkpoint resume, rigid-motion '
                  'objectivity, and same-parent tangents. Shear/torsion remain elastic and the 3D '
                  'basic-mode mappings use disclosed numerical derivatives. The fixed two-element '
                  'same-operator OpenSees comparison covers only the dense elastic branch. General '
                  'shear lag/uplift/contact, cyclic confined concrete, connector groups, member '
                  'features, warping coupling, analytic and production-scale sparse/material 3D '
                  'behavior, multi-turn rotation, independent external review, '
                  'committed-current-HEAD promotion, and release authority remain open.'],
  'profile': 'dense_elastic_native_sparse_axial_distributed_biaxial_fiber_and_partial_composite_corotational_timoshenko_frame3d.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Corotational 3D frame'},
 {'authority': 'bounded_local_stiffness_candidate',
  'category': 'element',
  'evidence': ['src/structural_analysis/elements/timoshenko_frame3d.py',
               'tests/test_p2_frame3d_candidates.py',
               'docs/p2-frame3d-candidates.md'],
  'id': 'element.timoshenko_frame_3d',
  'interfaces': ['internal_python'],
  'limitations': ['Linear prismatic local element only; effective shear areas must be explicit and '
                  'nonlinear/global integration is open.'],
  'profile': 'two_node_timoshenko_frame3d_shear_condensed.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Shear-deformable 3D frame element'},
 {'authority': 'bounded_local_energy_candidate',
  'category': 'element',
  'evidence': ['src/structural_analysis/elements/torsion_warping.py',
               'tests/test_p2_frame3d_candidates.py',
               'docs/p2-frame3d-candidates.md'],
  'id': 'element.torsion_warping',
  'interfaces': ['internal_python'],
  'limitations': ['Separate four-DOF linear kernel; not assembled into the 12-DOF frame and no '
                  'open-section stress or external validation authority.'],
  'profile': 'vlasov_hermite_twist_gradient_2node.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Vlasov torsion and warping kernel'},
 {'authority': 'geometry_generation_only',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/initial_imperfection.py',
               'tests/test_p2_frame3d_candidates.py',
               'docs/p2-frame3d-candidates.md'],
  'id': 'analysis.initial_imperfection_mesh',
  'interfaces': ['internal_python'],
  'limitations': ['One-member half-sine geometry only; no code amplitude, eigenmode scaling, '
                  'residual stress, nonlinear solve, or design authority.'],
  'profile': 'sinusoidal_member_bow_local_yz.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Explicit member initial-imperfection mesh'},
 {'authority': 'bounded_repository_benchmark_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/benchmark/stateful_corotational_steel_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_concrete_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_composite_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_linked_frame_cyclic.py',
               'tests/test_stateful_corotational_steel_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_concrete_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_composite_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_linked_frame_cyclic_benchmark.py',
               'docs/p2-cyclic-frame-candidates.md'],
  'id': 'analysis.cyclic_corotational_fiber_frames',
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Repository-generated steel, concrete, perfect-bond composite, and link cases '
                  'only; no published cyclic acceptance, confinement/bond-slip member integration, '
                  '3D response, or release authority.'],
  'profile': 'two_member_planar_material_state_commit_rollback.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Cyclic corotational fiber-frame benchmarks'},
 {'authority': 'bounded_numerical_comparison_without_hierarchy_credit',
  'category': 'verification',
  'evidence': ['src/structural_analysis/benchmark/lee_frame.py',
               'src/structural_analysis/benchmark/lee_frame_verification_candidate.py',
               'implementation/phase1/release_evidence/productization/verification_candidates/lee_frame/source_receipt.json',
               'implementation/phase1/release_evidence/productization/verification_candidates/lee_frame/execution_receipt.json',
               'implementation/phase1/release_evidence/productization/verification_candidates/lee_frame/scientific_decision.json',
               'implementation/phase1/release_evidence/productization/verification_hierarchy_evidence.candidate.json',
               'tests/test_lee_frame_snapthrough_benchmark.py',
               'tests/test_lee_frame_verification_candidate.py',
               'docs/phase2-lee-frame-snapthrough.md',
               'docs/lee-frame-formal-vnv-candidate.md'],
  'id': 'vv.published_lee_frame_candidate',
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['The fixed Lee-frame numerical decision passes, but publisher-source bytes, '
                  'source-use approval, independent clean-runner reproduction, formal operator '
                  'approval, completed Level 2 prerequisites, and Level 3 hierarchy credit are '
                  'absent.'],
  'profile': 'fixed_20_element_elastic_lee_frame_table11.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Published Lee-frame snap-through candidate'},
 {'authority': 'none',
  'category': 'element',
  'evidence': ['docs/p3-entry-gate.md', 'tests/test_p3_entry_gate.py'],
  'id': 'element.shell_plate',
  'interfaces': ['none'],
  'limitations': ['No canonical-core public shell or plate formulation; phase1 shell assets are '
                  'proxy, research, or technical evidence only.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Shell and plate elements'},
 {'authority': 'none',
  'category': 'interaction',
  'evidence': ['docs/p3-entry-gate.md', 'tests/test_p3_entry_gate.py'],
  'id': 'interaction.contact',
  'interfaces': ['none'],
  'limitations': ['No canonical-core public contact element, search, enforcement, state, or '
                  'externally validated solver profile.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Structural contact'},
 {'authority': 'none',
  'category': 'element',
  'evidence': ['docs/p3-entry-gate.md', 'tests/test_p3_entry_gate.py'],
  'id': 'element.cable',
  'interfaces': ['none'],
  'limitations': ['No canonical-core public cable formulation, prestress/sag state, nonlinear '
                  'solve integration, or external validation.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Cable elements'},
 {'authority': 'none',
  'category': 'analysis',
  'evidence': ['docs/p3-entry-gate.md', 'tests/test_p3_entry_gate.py'],
  'id': 'analysis.soil_structure_interaction',
  'interfaces': ['none'],
  'limitations': ['Phase1 SSI research assets do not establish a promoted canonical-core solver '
                  'profile, external V&V, or design authority.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Soil-structure interaction'},
 {'authority': 'none',
  'category': 'analysis',
  'evidence': ['docs/p3-entry-gate.md', 'tests/test_p3_entry_gate.py'],
  'id': 'analysis.staged_construction',
  'interfaces': ['none'],
  'limitations': ['No promoted activation/deactivation, state-transfer, load-history, checkpoint, '
                  'and external-validation contract in canonical core.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Staged construction'},
 {'authority': 'none',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/assembly/coupled_static.py',
               'tests/test_build_phase2_frame_shell_material_coupling_artifacts.py',
               'tests/test_mgt_coupled_frame_shell_sparse_equilibrium.py',
               'docs/p3-entry-gate.md'],
  'id': 'analysis.mixed_frame_shell_nonlinear',
  'interfaces': ['none'],
  'limitations': ['The two-DOF named seed and large sparse technical probe do not provide a '
                  'general shell element or mixed nonlinear product solve.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Mixed frame-shell nonlinear analysis'},
 {'authority': 'none',
  'category': 'execution',
  'evidence': ['docs/durable-job-service.md',
               'docs/p3-entry-gate.md',
               'tests/test_p3_entry_gate.py'],
  'id': 'execution.distributed',
  'interfaces': ['none'],
  'limitations': ['The durable job-service candidate is single-host; no consensus, remote '
                  'replication, multi-host scheduling, identity, or SLO evidence exists.'],
  'profile': 'p3_after_single_host_job_service_promotion',
  'public': False,
  'status': 'blocked',
  'title': 'Distributed execution'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/customer_shadow_evidence_status.json',
               'docs/p3-entry-gate.md',
               'tests/test_p3_entry_gate.py'],
  'id': 'evidence.customer_shadow_three',
  'interfaces': ['evidence'],
  'limitations': ['The validated completed-project customer-shadow count is 0/3; templates and '
                  'intake packets do not count as evidence.'],
  'profile': 'completed_project_customer_retained_metadata_minimum_3',
  'public': False,
  'status': 'blocked',
  'title': 'Three validated customer-shadow cases'},
 {'authority': 'none',
  'category': 'design',
  'evidence': ['docs/p3-entry-gate.md', 'tests/test_p3_entry_gate.py'],
  'id': 'design.code_modules',
  'interfaces': ['none'],
  'limitations': ['Optimization scripts and KDS input data are not an implemented, versioned, '
                  'reviewed, externally validated design-code authority module.'],
  'profile': 'p3_after_p0_p2_entry_gate',
  'public': False,
  'status': 'blocked',
  'title': 'Structural design-code modules'},
 {'authority': 'consumer_only',
  'category': 'application',
  'evidence': ['docs/workbench-v2.md', 'tests/frontend/workbench-v2-e2e.spec.ts'],
  'id': 'app.workbench_result_evidence',
  'interfaces': ['workbench'],
  'limitations': ['Workbench display and review decisions never create solver truth.'],
  'profile': 'typed_workbench_case_and_evidence_reader',
  'public': True,
  'status': 'bounded_public',
  'title': 'Workbench result and evidence review'},
 {'authority': 'orchestration_and_integrity_only',
  'category': 'application',
  'evidence': ['docs/durable-job-service.md',
               'src/structural_analysis/execution/job_service.py',
               'tests/test_durable_job_service.py',
               'tests/frontend/workbench-v2-job-contract.spec.ts'],
  'id': 'app.job_service_checkpoint_resume',
  'interfaces': ['internal_python', 'http_adapter', 'worker', 'workbench'],
  'limitations': ['Single-host candidate only; distributed consensus, production identity/TLS/SLO '
                  'evidence, remote replication, and release promotion remain open.'],
  'profile': 'sqlite_wal_content_addressed_single_host_exact_resume.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Job service checkpoint and resume'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['artifacts/manifests/engineering_reviewers.json',
               'artifacts/review/engineering_review_package.candidate.json',
               'scripts/build_engineering_review_package.py',
               'src/structural_analysis/schemas/engineering_review_package_v1.schema.json',
               'src/structural_analysis/schemas/engineering_reviewer_registry_v1.schema.json',
               'tests/test_engineering_review_package.py',
               'docs/engineering-review-package.md'],
  'id': 'evidence.engineering_review_package',
  'interfaces': ['evidence'],
  'limitations': ['The deterministic review-material and detached-signature verifier are '
                  'implemented, but the trusted reviewer registry is empty, the current candidate '
                  'is not a clean current HEAD, prerequisite Level 2/3 and deployment evidence is '
                  'missing, and no reviewer assertion or signature is attached.'],
  'profile': 'current_head_prerequisites_trusted_reviewer_ed25519.v1',
  'public': False,
  'status': 'blocked',
  'title': 'Signed engineering-review package'},
 {'authority': 'proposal_and_evaluation_only',
  'category': 'ai_control',
  'evidence': ['src/structural_analysis/ai/shadow_solver_controller.py',
               'src/structural_analysis/ai/offline_counterfactual.py',
               'artifacts/ai/offline_counterfactual_dataset.json',
               'artifacts/ai/shadow_policy_scorecard.json',
               'docs/offline-counterfactual-shadow-scorecard.md',
               'tests/test_ai_offline_counterfactual.py'],
  'id': 'ai.solver_shadow_control',
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Shadow proposals are not executed and cannot alter solver truth.',
                  'The checked-in scorecard is a repository contract fixture; v1 has no signed '
                  'independent-source attestation and guarded execution remains unavailable.'],
  'profile': 'deterministic_baseline_plus_replay_bound_offline_scorecard.v1',
  'public': False,
  'status': 'shadow_only',
  'title': 'AI solver shadow control'},
 {'authority': 'none',
  'category': 'ai_control',
  'evidence': ['docs/ai-shadow-solver-controller.md',
               'docs/offline-counterfactual-shadow-scorecard.md',
               'docs/p3-entry-gate.md'],
  'id': 'ai.guarded_execution',
  'interfaces': ['internal_python'],
  'limitations': ['No production action execution or autonomous engineering authority.',
                  'A repository-generated contract fixture cannot satisfy independent policy or '
                  'guard evidence.'],
  'profile': 'offline_counterfactual_and_guard_receipts_required',
  'public': False,
  'status': 'blocked',
  'title': 'Guarded AI execution'},
 {'authority': 'none',
  'category': 'backend',
  'evidence': ['docs/engine-v2-cpu-hip-fgmres-recurrence.md', 'docs/p3-entry-gate.md'],
  'id': 'backend.rocm_hip_production',
  'interfaces': ['hardware_runner'],
  'limitations': ['Residency, full-path parity, fallback, and hardware provenance gates remain '
                  'open.'],
  'profile': 'performance_track_after_cpu_sparse_and_external_vv',
  'public': False,
  'status': 'blocked',
  'title': 'ROCm/HIP production backend'})

def capabilities(*, public_only: bool = False) -> tuple[dict[str, Any], ...]:
    rows = CAPABILITY_ROWS
    if public_only:
        rows = tuple(row for row in rows if row['public'])
    return tuple(dict(row) for row in rows)
