"""Generated capability registry. Do not edit directly."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

CAPABILITY_SCHEMA_VERSION = 'structural-analysis-capabilities.v1'
CAPABILITY_AUTHORITY_RULES: dict[str, Any] = {'ai_truth_owner': 'none',
 'fallback_promotion_allowed': False,
 'gpu_track': 'performance_after_cpu_sparse_reference_and_external_vv',
 'solver_truth_owner': 'structural_analysis_core',
 'workbench_truth_owner': 'none'}
CAPABILITY_ROWS: tuple[dict[str, Any], ...] = ({'authority': 'validated_input_contract',
  'category': 'model_io',
  'evidence': ['tests/test_structural_analysis_core_api.py'],
  'id': 'model.neutral_canonical',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Only schema-declared entities and units are accepted.'],
  'profile': 'structural-analysis-canonical-model.v1',
  'public': True,
  'status': 'supported',
  'title': 'Neutral canonical model'},
 {'authority': 'input_translation_with_provenance',
  'category': 'model_io',
  'evidence': ['src/structural_analysis/io/midas/loader.py',
               'tests/test_structural_analysis_core_api.py'],
  'id': 'io.midas_mgt',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Unsupported records remain explicit; exact native round-trip is not closed.'],
  'profile': 'topology_and_supported_property_subset',
  'public': True,
  'status': 'bounded_public',
  'title': 'MIDAS MGT import'},
 {'authority': 'entity_scan_and_model_health_only',
  'category': 'model_io',
  'evidence': ['src/structural_analysis/io/ifc/loader.py',
               'tests/test_structural_analysis_core_api.py'],
  'id': 'io.ifc_model_health',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Not a general analysis-ready IFC structural-model compiler.'],
  'profile': 'ifc_step_model_health',
  'public': True,
  'status': 'bounded_public',
  'title': 'IFC model-health import'},
 {'authority': 'numerical_and_engineering_within_supported_elements',
  'category': 'analysis',
  'evidence': ['docs/authoritative-cpu-linear-solver.md',
               'tests/test_structural_analysis_core_api.py'],
  'id': 'analysis.linear_static',
  'interfaces': ['python_api', 'cli', 'workbench'],
  'limitations': ['No general shell, contact, staged-construction, or design-code authority.'],
  'profile': 'cpu_dense_or_scipy_sparse_supported_frame_truss',
  'public': True,
  'status': 'bounded_public',
  'title': 'Linear static analysis'},
 {'authority': 'numerical_within_explicit_frame_truss_mass_profile',
  'category': 'analysis',
  'evidence': ['docs/phase2-whole-model-modal-analysis.md',
               'tests/test_whole_model_modal_analysis.py'],
  'id': 'analysis.modal',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The public default is dense and no independent Level 2 comparison is promoted.'],
  'profile': 'dense_symmetric_generalized_eigen_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Whole-model modal analysis'},
 {'authority': 'numerical_within_explicit_preload_profile',
  'category': 'analysis',
  'evidence': ['docs/phase2-whole-model-linear-buckling.md',
               'tests/test_whole_model_buckling_analysis.py'],
  'id': 'analysis.linear_buckling',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The public default is dense and no independent Level 2 comparison is promoted.'],
  'profile': 'dense_symmetric_generalized_eigen_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Whole-model linear buckling'},
 {'authority': 'bounded_material_geometric_newton',
  'category': 'analysis',
  'evidence': ['docs/public-two-bar-nonlinear-truss.md',
               'src/structural_analysis/api/nonlinear_truss.py'],
  'id': 'analysis.nonlinear_two_bar_truss',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['The profile does not generalize to arbitrary truss or frame topology.'],
  'profile': 'symmetric_two_bar_material_geometric_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Nonlinear two-bar truss'},
 {'authority': 'exact_reaction_member_section_fiber_recovery',
  'category': 'analysis',
  'evidence': ['docs/public-rc-fiber-frame.md', 'tests/test_public_rc_fiber_frame_api.py'],
  'id': 'analysis.nonlinear_rc_fiber_frame_fixed_chord',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Serial cantilever only; zero prescribed movement; dense CPU load control.'],
  'profile': 'planar_serial_cantilever_explicit_rectangular_rc.v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'Fixed-chord RC fiber frame'},
 {'authority': 'comparison_contract_only_no_result_promotion',
  'category': 'result_contract',
  'evidence': ['docs/engine-v2-result-quantity-contract.md',
               'src/structural_analysis/engine_v2/contracts/result_quantity.py',
               'src/structural_analysis/schemas/result_quantity_catalog_v1.schema.json',
               'tests/test_result_quantity_catalog.py'],
  'id': 'contract.result_quantity_catalog',
  'interfaces': ['python_api', 'json_schema'],
  'limitations': ['Defines fixed SI units and comparison tolerances only; it cannot create solver '
                  'authority or make corotational output public.'],
  'profile': 'hashed_si_quantity_catalog_and_absolute_plus_relative_linf_v1',
  'public': True,
  'status': 'bounded_public',
  'title': 'ResultIR SI quantity and tolerance catalog'},
 {'authority': 'bounded_j1_j5_and_exact_engineering_recovery_candidate',
  'category': 'analysis',
  'evidence': ['docs/unified-nonlinear-frame-api.md',
               'docs/corotational-connected-frame2d.md',
               'docs/corotational-fiber-frame-native-sparse.md',
               'src/structural_analysis/api/nonlinear_frame.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_general.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_sparse.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_checkpoint_chain_io.py',
               'src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_engineering_recovery.py',
               'src/structural_analysis/schemas/unified_nonlinear_frame_result_v1.schema.json',
               'src/structural_analysis/schemas/corotational_fiber_frame_general_j1_j5_v1.schema.json',
               'tests/test_corotational_fiber_frame_general.py',
               'tests/test_corotational_fiber_frame_sparse.py',
               'tests/test_unified_nonlinear_frame_api.py',
               'examples/public_corotational_branching_frame.json'],
  'id': 'analysis.nonlinear_corotational_fiber_frame_2d',
  'interfaces': ['python_api', 'cli'],
  'limitations': ['Connected planar 2-128-node, 1-256-non-parallel-member load-control CPU dense '
                  'or native COO/CSR candidate with branching, support UX/UY/RZ subsets, '
                  'proportional nodal loads, and proportional prescribed displacement; '
                  'disconnected graphs, parallel members, releases, rigid offsets, distributed '
                  'loads, direct displacement control, production-scale conditioning, both '
                  'independent Level 2 comparisons, and release promotion remain open.'],
  'profile': 'corotational_connected_frame2d.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Corotational 2D fiber frame'},
 {'authority': 'bounded_native_coo_csr_and_fail_closed_exact_conditioning_candidate',
  'category': 'backend',
  'evidence': ['src/structural_analysis/assembly/stateful_corotational_fiber_frame2d_sparse.py',
               'src/structural_analysis/solvers/nonlinear/sparse_factorization.py',
               'src/structural_analysis/solvers/nonlinear/scalable_sparse_factorization.py',
               'src/structural_analysis/schemas/sparse_factorization_diagnostic_v1.schema.json',
               'src/structural_analysis/schemas/scalable_sparse_factorization_diagnostic_v1.schema.json',
               'tests/test_corotational_fiber_frame_sparse.py',
               'tests/test_sparse_factorization_diagnostics.py',
               'tests/test_scalable_sparse_factorization.py',
               'docs/sparse-factorization-conditioning-diagnostics.md'],
  'id': 'backend.nonlinear_sparse',
  'interfaces': ['python_api', 'cli', 'internal_python'],
  'limitations': ['The public exact-conditioning path remains bounded to 256 equations. A separate '
                  'standalone CPU-only blocked exact diagnostic is bounded to 1536 equations but '
                  'is not yet wired into a nonlinear 3D backend. Exact inverse-column conditioning '
                  'has quadratic work and does not close production-scale policy, performance or '
                  'memory evidence, external V&V, or release promotion.'],
  'profile': 'corotational_element_triplet_coalesce_sorted_csr_fp64_plus_blocked_exact_1536.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Native sparse nonlinear backend'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/release_evidence/productization/external_code_to_code_technical_execution_receipt.json',
               'implementation/phase1/release_evidence/productization/external_modal_buckling_technical_execution_receipt.json',
               'artifacts/vv/opensees_calculix_clean_runner/clean_runner_receipt.json',
               'benchmarks/clean-runners/opensees-calculix/run_clean_runner.py',
               'scripts/run_external_code_to_code_technical_receipt.py',
               'scripts/run_external_modal_buckling_technical_receipt.py',
               'scripts/run_external_vv_clean_runner.sh',
               'tests/test_external_code_to_code_technical_receipt.py',
               'tests/test_external_modal_buckling_technical_receipt.py',
               'tests/test_external_vv_clean_runner_contract.py',
               'docs/external-code-to-code-technical-execution.md'],
  'id': 'vv.opensees_level2',
  'interfaces': ['evidence'],
  'limitations': ['Fresh pinned technical comparisons and a same-operator container-isolated '
                  'replay pass narrowly, including an elastic-state public corotational portal '
                  'path, but independent operator attestation, legal review, material-nonlinear '
                  'breadth, and a Level 2 promotion receipt are absent.'],
  'profile': 'independent_operator_promotion_required',
  'public': False,
  'status': 'blocked',
  'title': 'OpenSees Level 2 verification'},
 {'authority': 'none',
  'category': 'verification',
  'evidence': ['implementation/phase1/release_evidence/productization/external_modal_buckling_technical_execution_receipt.json',
               'scripts/run_external_modal_buckling_technical_receipt.py',
               'tests/test_external_modal_buckling_technical_receipt.py',
               'docs/external-code-to-code-technical-execution.md'],
  'id': 'vv.second_solver_level2',
  'interfaces': ['evidence'],
  'limitations': ['Fresh pinned CalculiX comparisons pass narrowly, but independent operator '
                  'attestation, legal review, broader coverage, and a second-solver Level 2 '
                  'promotion receipt are absent.'],
  'profile': 'independent_operator_promotion_required',
  'public': False,
  'status': 'blocked',
  'title': 'Second independent solver Level 2 verification'},
 {'authority': 'bounded_source_bound_uniaxial_crack_band_candidate',
  'category': 'material',
  'evidence': ['src/structural_analysis/materials/concrete_damage.py',
               'src/structural_analysis/benchmark/fracture_energy_concrete.py',
               'src/structural_analysis/schemas/fracture_energy_concrete_mesh_objectivity_v1.schema.json',
               'artifacts/benchmarks/fracture_energy_concrete_mesh_objectivity.json',
               'scripts/build_fracture_energy_concrete_benchmark.py',
               'tests/test_fracture_energy_concrete.py',
               'docs/fracture-energy-concrete-mesh-objectivity.md'],
  'id': 'material.fracture_energy_concrete',
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Source-bound mesh-objectivity evidence is limited to a seeded single-crack '
                  'uniaxial RC tie. Arbitrary frame or shell localization, multiaxial concrete, '
                  'confinement, bond slip, published or external validation, independent '
                  'engineering review, and release promotion remain open.'],
  'profile': 'localized_crack_band_rc_tie_2_4_8_meshes.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Fracture-energy concrete'},
 {'authority': 'bounded_repository_benchmark_candidate',
  'category': 'analysis',
  'evidence': ['src/structural_analysis/benchmark/stateful_corotational_steel_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_concrete_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_composite_frame_cyclic.py',
               'src/structural_analysis/benchmark/stateful_corotational_linked_frame_cyclic.py',
               'tests/test_stateful_corotational_steel_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_concrete_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_composite_frame_cyclic_benchmark.py',
               'tests/test_stateful_corotational_linked_frame_cyclic_benchmark.py'],
  'id': 'analysis.cyclic_corotational_fiber_frames',
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Repository-generated steel, concrete, composite, and link cases only; no '
                  'published cyclic acceptance, 3D response, or release authority.'],
  'profile': 'two_member_planar_material_state_commit_rollback.v1',
  'public': False,
  'status': 'experimental',
  'title': 'Cyclic corotational fiber-frame benchmarks'},
 {'authority': 'consumer_only',
  'category': 'application',
  'evidence': ['docs/workbench-v2.md', 'tests/frontend/workbench-v2-e2e.spec.ts'],
  'id': 'app.workbench_result_evidence',
  'interfaces': ['workbench'],
  'limitations': ['Workbench display and review decisions never create solver truth.'],
  'profile': 'typed_workbench_case_and_evidence_reader',
  'public': True,
  'status': 'bounded_public',
  'title': 'Workbench result and evidence review'},
 {'authority': 'proposal_and_evaluation_only',
  'category': 'ai_control',
  'evidence': ['src/structural_analysis/ai/shadow_solver_controller.py',
               'docs/ai-shadow-solver-controller.md',
               'tests/test_shadow_solver_controller.py',
               'src/structural_analysis/ai/offline_counterfactual.py',
               'artifacts/ai/offline_counterfactual_dataset.json',
               'artifacts/ai/shadow_policy_scorecard.json',
               'docs/offline-counterfactual-shadow-scorecard.md',
               'tests/test_ai_offline_counterfactual.py'],
  'id': 'ai.solver_shadow_control',
  'interfaces': ['internal_python', 'evidence'],
  'limitations': ['Shadow proposals are not executed and cannot alter solver truth.',
                  'The checked-in scorecard is a repository contract fixture; v1 has no signed '
                  'independent-source attestation and guarded execution remains unavailable.'],
  'profile': 'deterministic_baseline_plus_replay_bound_offline_scorecard.v1',
  'public': False,
  'status': 'shadow_only',
  'title': 'AI solver shadow control'},
 {'authority': 'none',
  'category': 'ai_control',
  'evidence': ['docs/ai-shadow-solver-controller.md',
               'docs/offline-counterfactual-shadow-scorecard.md',
               'docs/structural-analysis-ai-engine-gap-ledger.md'],
  'id': 'ai.guarded_execution',
  'interfaces': ['internal_python'],
  'limitations': ['No production action execution or autonomous engineering authority.',
                  'A repository-generated contract fixture cannot satisfy independent policy or '
                  'guard evidence.'],
  'profile': 'offline_counterfactual_and_guard_receipts_required',
  'public': False,
  'status': 'blocked',
  'title': 'Guarded AI execution'},
 {'authority': 'none',
  'category': 'backend',
  'evidence': ['docs/engine-v2-cpu-hip-fgmres-recurrence.md',
               'implementation/phase1/release_evidence/productization/engine_v2_cpu_hip_fgmres_recurrence_receipt.json',
               'implementation/phase1/release_evidence/productization/engine_v2_hip_fgmres_stage4_status.json',
               'tests/test_engine_v2_hip_fgmres_stage4_status.py'],
  'id': 'backend.rocm_hip_production',
  'interfaces': ['hardware_runner'],
  'limitations': ['Residency, full-path parity, fallback, and hardware provenance gates remain '
                  'open.'],
  'profile': 'performance_track_after_cpu_sparse_and_external_vv',
  'public': False,
  'status': 'blocked',
  'title': 'ROCm/HIP production backend'})

def capabilities(*, public_only: bool = False) -> tuple[dict[str, Any], ...]:
    rows = CAPABILITY_ROWS
    if public_only:
        rows = tuple(row for row in rows if row['public'])
    return tuple(deepcopy(row) for row in rows)
